### ISSUE TITLE
Unable to delete message from "Messaging" 

### ISSUE THREAD

**Issue by rumsant** [shihjay2/nosh2#100]
If I click on the trash can icon next to a message, I'm asked to confirm if I'd like to delete the message, and if I click yes I am brought to an error page:

"Whoops, looks like something went wrong.
1/1
ErrorException in CoreController.php line 647:
Undefined index: patient_name
in CoreController.php line 647
..."

**Comment by shihjay2** [comment]
Fixed in commit 62e298f30ceecbf199f0f8fa91bca6bd0e4ee164
