### ISSUE TITLE
Chart sharing

### ISSUE THREAD

**Issue by ajinkyagadewar** [shihjay2/nosh2#103]
The provider authorization_endpoint has not been set. Make sure your provider has a well known configuration available.

What am I missing?

**Comment by shihjay2** [comment]
Please provide more information how are you getting to chart sharing - do you have HIE of One AS installed on the same domain as your NOSH install?

**Comment by ajinkyagadewar** [comment]
No I have installed it on the different domain and different server. Can you please tell me the right process to do it.

**Comment by shihjay2** [comment]
Out of scope; referring to https://github.com/shihjay2/hieofone-as
