### ISSUE TITLE
How practice can get OIDC client id

### ISSUE THREAD

**Issue by ajinkyagadewar** [shihjay2/nosh2#104]
Hello Sir:

I have setup nosh, oidc and openid servers. Though I got a bit of understand but can you please make me understand how it overall works as you designed it? Is there a place where practice can register itself and get client id which gets saved in database.

Please help in understanding.

Thanks.

**Comment by shihjay2** [comment]
Patient has to have an account to the practice NOSH (not patient NOSH) and enter their domain where their patient NOSH and HIE of One AS resides to initiate dynamic registration of the practice NOSH to the patient's HIE of One AS (is that what you mean by OIDC and OpenID servers?)

**Comment by ajinkyagadewar** [comment]
Sir:

It is still confusing. Would it be possible for you to have a Skype call because I am very interested in this solution?

Thanks.
