### ISSUE TITLE
Weight to Height Growth Chart Gives Exception when no vitals are entered

### ISSUE THREAD

**Issue by StreckerCM** [shihjay2/nosh2#106]
While checking the newly setup nosh-in-a-box with all the patients added.  I found that all the growth charts except "Weight to Height" will load correctly.  It may be throwing the error because we have patients but since it is newly setup there are no encounters with vitals entered so the vitals table is empty.

## Steps to Reproduce

1. Add new patient
2. Go to patient profile
3. Select Growth Charts
4. Choose Weight to Height

> **ErrorException in Controller.php line 8775: Trying to get property 'pedsage' of non-object**
> 
>     in Controller.php line 8775
>     at HandleExceptions->handleError('8', 'Trying to get property 'pedsage' of non-object', '/noshdocuments/nosh2/app/Http/Controllers/Controller.php', '8775', array('sex' => 'm', 'pid' => '140', 'data' => array('patient' => array(), 'graph_y_title' => 'kg', 'graph_x_title' => 'cm'), 'query' => null)) in Controller.php line 8775
>     at Controller->gc_weight_height('m', '140') in ChartController.php line 6251
>     at ChartController->growth_chart(object(Request), 'weight-height')
>     at call_user_func_array(array(object(ChartController), 'growth_chart'), array(object(Request), 'type' => 'weight-height')) in Controller.php line 55
>     at Controller->callAction('growth_chart', array(object(Request), 'type' => 'weight-height')) in ControllerDispatcher.php line 44
>     at ControllerDispatcher->dispatch(object(Route), object(ChartController), 'growth_chart') in Route.php line 189
>     at Route->runController() in Route.php line 144
>     at Route->run(object(Request)) in Router.php line 653
>     at Router->Illuminate\Routing\{closure}(object(Request)) in Pipeline.php line 53
>     at Pipeline->Illuminate\Routing\{closure}(object(Request)) in CheckPatient.php line 19
>     at CheckPatient->handle(object(Request), object(Closure)) in Pipeline.php line 137
>     at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
>     at Pipeline->Illuminate\Routing\{closure}(object(Request)) in PostAuth.php line 55
>     at PostAuth->handle(object(Request), object(Closure)) in Pipeline.php line 137
>     at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
>     at Pipeline->Illuminate\Routing\{closure}(object(Request)) in VerifyCsrfToken.php line 65
>     at VerifyCsrfToken->handle(object(Request), object(Closure)) in Pipeline.php line 137
>     at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
>     at Pipeline->Illuminate\Routing\{closure}(object(Request)) in Authenticate.php line 33
>     at Authenticate->handle(object(Request), object(Closure)) in Pipeline.php line 137
>     at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
>     at Pipeline->Illuminate\Routing\{closure}(object(Request)) in CheckInstall.php line 85
>     at CheckInstall->handle(object(Request), object(Closure)) in Pipeline.php line 137
>     at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
>     at Pipeline->Illuminate\Routing\{closure}(object(Request)) in ShareErrorsFromSession.php line 49
>     at ShareErrorsFromSession->handle(object(Request), object(Closure)) in Pipeline.php line 137
>     at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
>     at Pipeline->Illuminate\Routing\{closure}(object(Request)) in StartSession.php line 64
>     at StartSession->handle(object(Request), object(Closure)) in Pipeline.php line 137
>     at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
>     at Pipeline->Illuminate\Routing\{closure}(object(Request)) in AddQueuedCookiesToResponse.php line 37
>     at AddQueuedCookiesToResponse->handle(object(Request), object(Closure)) in Pipeline.php line 137
>     at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
>     at Pipeline->Illuminate\Routing\{closure}(object(Request)) in EncryptCookies.php line 59
>     at EncryptCookies->handle(object(Request), object(Closure)) in Pipeline.php line 137
>     at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
>     at Pipeline->Illuminate\Routing\{closure}(object(Request)) in Pipeline.php line 104
>     at Pipeline->then(object(Closure)) in Router.php line 655
>     at Router->runRouteWithinStack(object(Route), object(Request)) in Router.php line 629
>     at Router->dispatchToRoute(object(Request)) in Router.php line 607
>     at Router->dispatch(object(Request)) in Kernel.php line 268
>     at Kernel->Illuminate\Foundation\Http\{closure}(object(Request)) in Pipeline.php line 53
>     at Pipeline->Illuminate\Routing\{closure}(object(Request)) in BeforeMiddleware.php line 20
>     at BeforeMiddleware->handle(object(Request), object(Closure)) in Pipeline.php line 137
>     at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
>     at Pipeline->Illuminate\Routing\{closure}(object(Request)) in CheckForMaintenanceMode.php line 46
>     at CheckForMaintenanceMode->handle(object(Request), object(Closure)) in Pipeline.php line 137
>     at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in Pipeline.php line 33
>     at Pipeline->Illuminate\Routing\{closure}(object(Request)) in Pipeline.php line 104
>     at Pipeline->then(object(Closure)) in Kernel.php line 150
>     at Kernel->sendRequestThroughRouter(object(Request)) in Kernel.php line 117
>     at Kernel->handle(object(Request)) in index.php line 53

**Comment by shihjay2** [comment]
I've updated the code to hide the growth chart menu if there are no vitals recorded for a patient even if they are pediatric.  Perform the update_system command.  Fixed in commit 01d54b8d2735ff8945b311b778d619ea7f650d8a.
