### ISSUE TITLE
When entering billing on back-to-back encounters it will sometimes post to the previous record

### ISSUE THREAD

**Issue by StreckerCM** [shihjay2/nosh2#107]
We have experienced an issue with Nosh when entering billing on back-to-back encounters.  It sometimes will post the billing information to the previously edited billing record.  This usually happens after editing a previous billing record entry.

## Steps to Reproduce
1. Entering encounters
2. Edit all encounter information
3. Then go to billing and update billing information
4. Search for next client/encounter
5. Edit all encounter information
6. Then go to billing for next encounter, sometimes the date is wrong as it is trying to add to the previous claim and not the current one.   If you enter the billing amount it will appear on the previous record.

## Work Around
log in and out and usually fixes it. 

## Tested On
Chrome and Safari on MacOS

**Comment by shihjay2** [comment]
Fixed in commit 81fdaff22e4b79d4981ddc8cef53cddb97961ec3.  Please test and confirm.

**Comment by StreckerCM** [comment]
Thanks, this looks to have resolved it when you go between patients but we did see the issue crop up when you edit multiple back-to-back billing records for the same patient.

**Comment by StreckerCM** [comment]
Little more information: It seems to work fine if the person has two billing entries that need updated but if they have more then that it has an issue on the 3rd one.

**Comment by shihjay2** [comment]
I need more info - when you're talking about billing entries, are you talking about the action "Add Procedure Code" or is it something else?

**Comment by StreckerCM** [comment]
Let me know if this helps "yes when on the adding a procedure code for an encounter entering all the information for an encounter and then it will post it to the last encounter entered instead of the one currently being worked on. not always now, seemed better than before but was still having intermittent issues since update. now i'm all caught up on back entering and not sure if will run across issue in the future."

**Comment by shihjay2** [comment]
I made a few more optimizations to see if I can make the encounter relationship more hardy in case there is a different workflow in commit 3e0f1a16533eb040552d7bcb2a8021d966cced07

**Comment by StreckerCM** [comment]
I will let you know when I am able to get a retest result.  Currently billing is all caught up.
