### ISSUE TITLE
Billing Notes and Outstanding Balances Report

### ISSUE THREAD

**Issue by StreckerCM** [shihjay2/nosh2#108]
The billing notes will show up on the Outstanding Balances Report under financials even if the account balance is zero.  Since there is no way in the UI to remove a billing note this means that that patient will always be displayed on this report because a note was entered.

## Expectation
Patient will only show on the Outstanding Balance Report when their balance is greater then zero even if a billing note was entered 

![outstanding_balances_report](https://user-images.githubusercontent.com/3030358/39677917-c8024454-5148-11e8-9b9f-817e97ac5aab.png)

**Comment by shihjay2** [comment]
Made updates on the Outstanding Balances function in commit e01ba64642def69bed6c1e639c25caf36e3478cc

**Comment by StreckerCM** [comment]
Thank you that has fixed this issue
