### ISSUE TITLE
Issue with TrustProxies

### ISSUE THREAD

**Issue by authemany2k** [shihjay2/nosh2#112]
I tried to run this code in my Laragon environment and am getting this issue.
Please what is the solution

"Declaration of App\Http\Middleware\TrustProxies::handle($request, Closure $next) should be compatible with Fideloper\Proxy\TrustProxies::handle(Illuminate\Http\Request $request, Closure $next) ◀"

**Comment by shihjay2** [comment]
If you are not using a reverse proxy in your environment, you can comment out the Trust proxies declaration in the Kernel.php for the global middleware setting.  I don't use Laragon so I'm not sure why it's throwing the error yet.

**Comment by shihjay2** [comment]
See commit 011c2b6b5501b437e47ee22fbf4fc3ed6f2f5fc3 for fix.

**Comment by authemany2k** [comment]
Thanks Dr. Shihjay I will try out tomorrow. Thanks for your quick response On Jul 9, 2018 18:19, "Michael Shihjay Chen, MD" <notifications@github.com> wrote:If you are not using a reverse proxy in your environment, you can comment out the Trust proxies declaration in the Kernel.php for the global middleware setting.  I don't use Laragon so I'm not sure why it's throwing the error yet.
