### ISSUE TITLE
Undefined index: refresh_token

### ISSUE THREAD

**Issue by authemany2k** [shihjay2/nosh2#113]
Hi Dr. Shihjay 

Am getting this errror while trying to authenticate through google.

'Undefined index: refresh_token'

from this function

 public function googleoauth(Request $request)
    {
        $url = route('googleoauth');
        $google = new Google_Client();
        $google->setRedirectUri($url);
        $google->setApplicationName('NOSH ChartingSystem');
        $google->setClientID(env('GOOGLE_KEY'));
        $google->setClientSecret('GOOGLE_SECRET');
        $google->setAccessType('offline');
        $google->setApprovalPrompt('force');
        $google->setScopes(array('https://mail.google.com/'));
        if (isset($_REQUEST["code"])) {
            $credentials = $google->authenticate($_GET['code']);
            $data['google_refresh_token'] = $credentials['refresh_token'];
            DB::table('practiceinfo')->where('practice_id', '=', Session::get('practice_id'))->update($data);
            return redirect()->route('setup_mail_test');
        } else {
            $authUrl = $google->createAuthUrl();
            header('Location: ' . filter_var($authUrl, FILTER_SANITIZE_URL));
            exit;
        }
    }

**Comment by authemany2k** [comment]
No ssl on the subdomain that am using to host it because it's a subdomain of my main site. 
What can i do to go pass this stage. I tried to follow your steps on wiki still i cannot go beyond this stage. Thanks in anticipation for your help

**Comment by authemany2k** [comment]
I HAVE RESOLVED THIS ISSUE. You DIDNT INCLUDE ENV IN YOUR GOOGLE_SECRET. VARIABLE

**Comment by shihjay2** [comment]
Please clarify.  There is a new Setup Mail as an admin user (setup_mail) that fills in the .env file with the appropriate variable and values.  There instructions in the Wiki does not reflect these recent changes.

**Comment by authemany2k** [comment]
This is exactly what i did. Your original code look like this 
$google->setClientSecret('GOOGLE_SECRET');
While i changed mine to 
$google->setClientSecretENV(('GOOGLE_SECRET')) ;

**Comment by authemany2k** [comment]
Yeah! that is great!!

**Comment by shihjay2** [comment]
Fixed in commit 3efde57bee1c82b82803d144f15def18465280c0

**Comment by authemany2k** [comment]
No ssl on the subdomain that am using to host it because it's a subdomain of my main site. What can i do to go pass this stage. Thanks for your support. On Jul 11, 2018 15:26, "Michael Shihjay Chen, MD" <notifications@github.com> wrote:Verify that you have a valid SSL redirect URI and that you have followed the instructions in the Wiki https ://github.com/shihjay2/nosh-in-a-box/wiki/How-to-get-Gmail-to-work-with-NOSH
