### ISSUE TITLE
NOSH Allergy Inactivation Bug

### ISSUE THREAD

**Issue by grantyn** [shihjay2/nosh2#114]
When trying to inactivate an allergy I get the follow error (screenshot):

https://www.dropbox.com/s/qq0x91zho3o23fu/Screenshot%202018-07-25%2013.00.31.png?dl=0

Grant

**Comment by shihjay2** [comment]
Just fixed in commit bec9d35d56426985b5b3e0fdb440d0acaf6b8a6b.  Run https://<domain>/nosh/update_system to update to latest version.
