### ISSUE TITLE
Auto updating broken?

### ISSUE THREAD

**Issue by sahoahfoa** [shihjay2/nosh2#115]
My nosh installation is stuck on commit 60947e8ec73ee8c7a6428799db2e960f20bb1ee3. It looks like commit e10a8c8d3413b7f0f9ad5b5c221dc4a333f2e761 took out the http call to update_system. Is there another mechanism in-place that supposed to be updating nosh?

**Comment by shihjay2** [comment]
Yes, you can update manually be either clicking on Update System in the menu when you click on the username after you login.  You can also do the update_system route to do it manually.  There are some changes that are related to an MVP release for the patient centered NOSH and I didn't want to inadvertently break other systems during the transition.  Once the new commits calm down and there has been enough time to uncover any bugs, I will consider reactivating the auto update script.  Thanks for your patience!
