### ISSUE TITLE
Error following update

### ISSUE THREAD

**Issue by rumsant** [shihjay2/nosh2#117]
I updated the Nosh system and following the update I am unable to access even the login screen.

I get a page that says:

"ErrorException in BaseProvider.php line 124:
File '/noshdocuments/nosh2/public/assets/css/jquery.fancybox.css' does not exist (View: /noshdocuments/nosh2/resources/views/layouts/app.blade.php) (View: /noshdocuments/nosh2/resources/views/layouts/app.blade.php)"

This is quite bad for me. Any suggestions appreciated.

**Comment by shihjay2** [comment]
Are you able to SSH to your system and see if that file exists and to list
permissions (ls -la).

**Comment by rumsant** [comment]
I am able to do that, and I see that it does not exist.

Is that a new file I need to add, or did it somehow get deleted during the update?

**Comment by shihjay2** [comment]
Yes it somehow got deleted during the update which is odd since it was not
deleted or removed in the repository.  I wonder if the update halted
somehow.  Can you show me the contents of the .version file in
/noshdocuments/nosh2

**Comment by rumsant** [comment]
f169a2d3be04a627cd067f9fd7a2b1cbfeb05928

**Comment by rumsant** [comment]
Not sure why, but it isn't publishing the entire number/letter string I'm typed in above.

**Comment by shihjay2** [comment]
Overwrite the contents of that version file (sudo nano .version) with this
7e85e8a463b88310cf125e085d857ec8b436497a

Then save it.

Then do update_system again to make sure we got all the changes.

**Comment by shihjay2** [comment]
Github truncates the numbers for the version numbers.  You can click on it and copy the end segement of the URL if you can't get to it; or this 
`7e85e8a463b88310cf125e085d857ec8b436497a`

**Comment by rumsant** [comment]
After update I get message:

"System Updated with version f169a2d3be04a627cd067f9fd7a2b1cbfeb05928 from 7e85e8a463b88310cf125e085d857ec8b436497a 
Nothing to migrate."

But I get the same error message about the fancybox.css file.

**Comment by shihjay2** [comment]
Do the following commands
```
cd /noshdocuments/nosh2/public/assets/css
wget https://raw.githubusercontent.com/shihjay2/nosh2/master/public/assets/css/jquery.fancybox.css
sudo chown www-data:www-data jquery.fancybox.css
sudo chmod 777 jquery.fancybox.css
```

Then try again

**Comment by rumsant** [comment]
Not sure if I was supposed to update after that. I didn't.
I just tried to access the login page and this was the result:

"File '/noshdocuments/nosh2/public/assets/js/jquery.fancybox.js' does not exist (View: /noshdocuments/nosh2/resources/views/layouts/app.blade.php) (View: /noshdocuments/nosh2/resources/views/layouts/app.blade.php)"

**Comment by shihjay2** [comment]
Do the following commands
```
cd /noshdocuments/nosh2/public/assets/js
wget https://raw.githubusercontent.com/shihjay2/nosh2/master/public/assets/js/jquery.fancybox.js
sudo chown www-data:www-data jquery.fancybox.js
sudo chmod 777 jquery.fancybox.js
```
Check if this file (2018_07_14_190507_add_message_id_to_image_table.php) exists
```
cd /noshdocuments/nosh2/database/migrations
ls
```
if not, then 
```
cd /noshdocuments/nosh2/database/migrations
wget https://raw.githubusercontent.com/shihjay2/nosh2/master/database/migrations/2018_07_14_190507_add_message_id_to_image_table.php
sudo chown www-data:www-data 2018_07_14_190507_add_message_id_to_image_table.php
sudo chmod 655 2018_07_14_190507_add_message_id_to_image_table.php
```
then do https://.../nosh/update_system/composer_install
then do https://.../nosh/update_system/migrate

**Comment by rumsant** [comment]
All praise be to shihjay2.

That seems to have done it.

So to recap, what? I missed an update interval (7/14/2018), and that caused this latest update to fail because I was missing some components?

**Comment by shihjay2** [comment]
For some reason your system did not want to update this commit 
77dd944c632beaf966c837dfe3070830dbbddad2
which was posted 2 months ago,  Where you missing the migration file too?  If you did have the migration file then maybe there was something weird with your permissions on the public/assets directories; you might want to check that the permissions are set to 777 - read write to all
`chmod 777 -R /noshdocuments/nosh/public`

**Comment by rumsant** [comment]
I did not have the file you mentioned. I had to wget that as well.

**Comment by shihjay2** [comment]
Well, I'm glad we were able to rescue your system; hopefully it should not happen again (that was a big commit that got skipped) - had some significant changes in preparation for the patient health record aspect of NOSH and HIE of One at that time.  Will mark it closed.

**Comment by rumsant** [comment]
Thank you!
