### ISSUE TITLE
Schedule Infinite Loading On Post

### ISSUE THREAD

**Issue by Tohm3** [shihjay2/nosh2#121]
After scheduling an App. on from the Patient Portal the loading screen does not go away and unless the page is refreshed the App doesn't show up. (It does seem to post the App. tho, one just needs to refresh manually after esc'n the load screen)

**Comment by shihjay2** [comment]
Please confirm in your system that your e-mail setup is functioning
correctly.  Login as Admin and please report back to me what is set and
what happens with testing (happens after you save the settings on the Setup
E-mail page.

**Comment by Tohm3** [comment]
I have set up email. It works fine, but when i select email service from the admin dashboard it still shows the screen to setup the mail service.

**Comment by shihjay2** [comment]
It looks like your email setup is not correct. If the test fails, you will
end up returning back to the email setup page. What type of email service
do you use?

**Comment by Tohm3** [comment]
but the email works fine, that's the thing. I have godaddy domain, and I run my email off a cpanel server hosted online. I use the IMAP and POP3 protocols.

**Comment by shihjay2** [comment]
So you set up the email service as Custom and filled out the appropriate
fields?  Are you able to send reminders through NOSH?  When you open a
patient's chart and click on demographics, Edit on Contacts and press Test
Reminder (you might want to use a dummy patient account with your e-mail
address), do you get the corresponding email?

**Comment by Tohm3** [comment]
Yes, i did use Custom. Yep, test reminders go through quite well (speedy, consistent).

**Comment by shihjay2** [comment]
When you try to set up the appointment as a provider for the same patient,
do you get any freezes?  Is this for all patients trying to set up an
appointment through the portal?  I could not replicate this issue, so I
wonder if it's an email address issue for the patient.

**Comment by Tohm3** [comment]
incidentally, no, when i set up the App. as the provider it works fine. Yes, the issue seems to be present for all (mind you i only have 2 test patients now) patients.

**Comment by shihjay2** [comment]
Are you able to pull up a console window of your browser (Network tab if
you're use Chrome specificallY) you try to make the appointment and can you
send a screenshot of the error?  It sounds like some type of setup error
but I can't pinpoint where the problems is in your system.

**Comment by Tohm3** [comment]
So an update on this, i had originally tried MS Edge and Chrome to see if the error was specific to FireFox (which is what is use) but now after restarting my VagrantBox and testing in Chrome and error is no longer present (not even in Firefox). I don't know what happened but it works now *shrug*. Mind you this error had been consistent for a few days now even after multiple Vagrant reloads. *shrug*
