### ISSUE TITLE
missing text in instructions?

### ISSUE THREAD

**Issue by dorothythayer** [shihjay2/nosh2#128]
[from instructions on Wordpress site:](https://noshemr.wordpress.com/download-2/)
It is not clear to me what  **item** is to be replaced with the IP address.  Is something missing?
Step 7: 
Important
If you are running NOSH inside a local area network and if you have a domain name assigned to your network, you need to make one change to Vagrantfile to allow users outside of your network to access NOSH. ...
Mac OS X: ...
In this example, again, 192.168.1.1 is your default gateway (router) IP address.
Once you have the router IP address, replace the **item** near the bottom of the Vagrantfile with the IP address that you have identified above. Then remove the # characters in 3 lines before the end line. This line starts with config.vm.provision "shell",
Thank you.

**Comment by shihjay2** [comment]
**Item** refers to these lines in the Vagrantfile file
```
# Allow NOSH-in-a-Box to be accessible outside your LAN
  # replace <ip gateway> to the IP address of your router (such as 192.168.1.1)
  # config.vm.provision "shell",
  #   run: "always",
  #   inline: "route del default; route add default gw <ip gateway>"
```
change it to this (note the missing # at the beginning of the last 3 lines) and follow the instructions in the 2nd line once you have found the IP address of your router in the instructions above.

```
# Allow NOSH-in-a-Box to be accessible outside your LAN
  # replace <ip gateway> to the IP address of your router (such as 192.168.1.1)
config.vm.provision "shell",
  run: "always",
  inline: "route del default; route add default gw <ip gateway>"

**Comment by dorothythayer** [comment]
thank you.
