### ISSUE TITLE
CCDA export of individual chart

### ISSUE THREAD

**Issue by rumsant** [shihjay2/nosh2#130]
Attempting to export an individual CCDA fails for me. The developer console give me:

ErrorException (E_NOTICE)
Undefined variable: hippa_role_code

I have been trying to figure out if I'm missing some kind of information in my setup, but I'm unable to locate anything called hippa_role_code.

**Comment by rumsant** [comment]
I believe I found my problem. I hadn't indicated a "Provider Role" in the records release. Once I did this it appears to have worked.
Perhaps "Provider Role" should be made a mandatory field since it seems to break the CCDA export.

**Comment by shihjay2** [comment]
Fixed in commit e2dbf9ca519d5e967281b011a1e3b7627da3c505
