### ISSUE TITLE
Undefined index: "LAG"

### ISSUE THREAD

**Issue by rodortega** [shihjay2/nosh2#132]
https://github.com/shihjay2/nosh2/blob/ab0c002236b15a4d41a809dadb7d3c5c36f70dc3/app/Http/Controllers/CoreController.php#L6527

https://github.com/shihjay2/nosh2/blob/ab0c002236b15a4d41a809dadb7d3c5c36f70dc3/app/Http/Controllers/CoreController.php#L6563

When I try to add a new Practice Group, and if I don't pick United States as a country, It will give an error **Undefined Index: "LAG"** or any state not from U.S.

**Comment by shihjay2** [comment]
Fixed in commit ba9e0ab44f229a7b601f4f5151543e39187a5ed3.
