### ISSUE TITLE
Possible bug blocking add patient

### ISSUE THREAD

**Issue by dcmack** [shihjay2/nosh2#135]
Was testing upgrade to latest version.  Noticed when trying to add patient, I got an error that showed the insert had an extra field.
![image](https://user-images.githubusercontent.com/13219976/72582102-a6f92700-38af-11ea-97b6-c423c6852a6f.png)
This field appears 2x in the code in CoreController.php - once on line 60 and again a few lines later.  Based on the migrations file, it seems like the 2nd instance is desired and the first should be removed since there is no "date_added" field that appears in the demographics table - the cause of the error being thrown.

**Comment by shihjay2** [comment]
Fixed in commit 17fd94f086231aa6b5dc115a011f85fc44538f54

**Comment by dcmack** [comment]
Confirmed issue solved by commit 17fd94f!  Thanks for the super-quick turnaround!
