### ISSUE TITLE
Imaging provider bug

### ISSUE THREAD

**Issue by tebaniel** [shihjay2/nosh2#143]
![Captura de Pantalla 2020-08-20 a la(s) 20 04 35](https://user-images.githubusercontent.com/69996882/90840739-68818a00-e320-11ea-9e8a-de019fc54644.png)
I add Imaging provider, but when I want to select one, the combobox don't show nothing and I can't add Imaging Order.

Thanks!

**Comment by shihjay2** [comment]
Fixed in commit 862529d5b746a5b1e443386601e5c60a62347615
