### ISSUE TITLE
How to configure

### ISSUE THREAD

**Issue by joanwilly** [shihjay2/nosh2#145]
Hi, 

I installed NOSH at localhost. I could configure basics (admin, provider, practice, etc). But I can't add patients, I can't manage appointments... Top menu is very different compared to the Noshchartingsystem demo: In my version I see menu items like "Email service", "Database" or "Export". But not items like "Schedule", "Financial", "Configure", etc. It's like I can't go beyond a very basic setup. 

Is something missing? Thanks in advance!

**Comment by shihjay2** [comment]
It appears you are still logged in as an Administrator user - which is the initial user to get set up when you first install NOSH.  If you created a Provider user as you indicated, you need to log out and log in using credentials for the Provider user to see the menu you and the ability to add patients as you indicated.

**Comment by joanwilly** [comment]
I can't. When I created the provider user, it didn't ask me for a Username and Password. It only asked me to introduce first name, last name, etc. But not credentials. So I saved and tried to set credentials editing the provider info, and it appears a "Username" field, but it has a grey background and you can't write there, although it's considered a requiered field (which blocks you form saving the form again). I didn't receive anything at the email introduced as a provider either.

**Comment by shihjay2** [comment]
If you didn't configure an email service (which is common in a localhost setting), you can create your password manually by clicking on the link below the Provider user name (it shows a link with accept_invitation within it) as the Administrator user which takes you to a page to create your password.

**Comment by joanwilly** [comment]
Hey, it seems to work fine now, with your instructions. Thank you very much! I really appreciate it.
