### ISSUE TITLE
Demo_patient bug

### ISSUE THREAD

**Issue by DeGroote99** [shihjay2/nosh2#151]
I was able to login as a patient and then had the ability to add medications to my chart. I also noticed that when I reviewed the documents, the PDF showed a dr note signed by patient

**Comment by shihjay2** [comment]
Adding medications to the chart by the patient is an intended feature; if added by the patient, the medication listing has a red background indicating that the medication needs to be reconciled by the physician.  In a future update, a patient can no longer generate his/her own doctor's letter; thanks for pointing this out.

**Comment by shihjay2** [comment]
Fixed in commit 8a7e6e1b15493371519f426c9096c7e9ae3d6f93
