### ISSUE TITLE
error with vagrant up

### ISSUE THREAD

**Issue by DeGroote99** [shihjay2/nosh2#152]
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "1723cfad-8110-47df-af40-ef4371ae8f36", "--type", "headless"]

Stderr: VBoxManage: error: The virtual machine 'nosh_default_1609373367298_85919' has terminated unexpectedly during startup with exit code 1 (0x1)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine

**Comment by shihjay2** [comment]
[As indicated](https://github.com/shihjay2/nosh-in-a-box/blob/master/readme.md) in the readme, NOSH-in-a-Box will soon be depreciated and no longer supported, there are known issues with Vagrant and PHP versions needed to meet compatibility with Laravel 8.0. To install NOSH, it is now recommended to try [Docker NOSH](https://github.com/shihjay2/docker-nosh) instead.

**Comment by DeGroote99** [comment]
I was having problem with docker for desktop, but I see you made some changes yesterday. Will try again when I get to office. FYI my plan is to fork for surgery and contribute. Especially in light of the new CMS E&M fee structure for 2021
