### ISSUE TITLE
fopen(/dev/urandom)

### ISSUE THREAD

**Issue by mohammadmahboubeh** [shihjay2/nosh2#155]
Hello Dr.

I am trying to add new physician but when I save the information I got this error message:
![1](https://user-images.githubusercontent.com/46927354/103479339-1aa48480-4dde-11eb-8f0f-6e3595d91018.PNG)
![22](https://user-images.githubusercontent.com/46927354/103479340-1b3d1b00-4dde-11eb-883d-0c9253d445f7.PNG)

**Comment by shihjay2** [comment]
Based on your screenshots, it looks like you're using xampp on Windows which does not have a /dev/urandom file - best to run it off of Docker which includes all the dependencies needed for NOSH.
