### ISSUE TITLE
Adding new physician 

### ISSUE THREAD

**Issue by mohammadmahboubeh** [shihjay2/nosh2#161]
Trying to add new physician the status is added but the list is empty... Please advise

![2](https://user-images.githubusercontent.com/46927354/105410398-ee449100-5c42-11eb-8952-d4ac24bd0829.PNG)
![11](https://user-images.githubusercontent.com/46927354/105410401-ef75be00-5c42-11eb-8bca-c6f824880474.PNG)

**Comment by mohammadmahboubeh** [comment]
![Uploading 22.PNG…]()

**Comment by shihjay2** [comment]
I see the database command and the group_id seems to indicate you added an assistant user, not a physician user (group_id should be 2, not 3).  So the user exists but not when you look on your active physician list, it should show up in your active assistant list.

**Comment by mohammadmahboubeh** [comment]
Actually I added a physician and an assistant as well but they did not appear on the list

**Comment by mohammadmahboubeh** [comment]
![1](https://user-images.githubusercontent.com/46927354/105460080-4fe51980-5c9c-11eb-8d44-47da9d82dcee.PNG)
![2](https://user-images.githubusercontent.com/46927354/105460085-51164680-5c9c-11eb-97e2-111d7d2b1c5f.PNG)

**Comment by shihjay2** [comment]
I'm looking also at your database command and it's missing an 'active' field (should show up between the 'group_id' and 'practice_id' fields) and it's coming up null in the database query; can't seem to replicate this in other deployments with the latest commit - what database type and version are you using if not using docker-nosh?

**Comment by mohammadmahboubeh** [comment]
I am using Firefox browser and Mysql 8.0.22 on Ubuntu 20.04 and I installed it through this command: sudo apt install mysql-server php7.4-mysql

Thanks,

**Comment by mohammadmahboubeh** [comment]
I tried to fill "active" field manually through MYSQL command it showed up in the list!!

**Comment by shihjay2** [comment]
I tested this using Firefox browser 84.0.2 and I was not able to replicate the error.  I can't say I understand why this is happening as the active field value should have been passed along via the POST request - manually adding the active field value via command line should not be the experience for this.

If you try to add another user again, can you inspect the network (in Firefox -> 3 line icon button -> Web Developer -> Network and when you submit the form, can you capture all of the POST request values being sent?

**Comment by mohammadmahboubeh** [comment]
Got new error:

![Screenshot from 2021-01-22 19-24-44](https://user-images.githubusercontent.com/46927354/105517113-b2173c00-5ce7-11eb-8cbc-6a36a6db264a.png)

**Comment by mohammadmahboubeh** [comment]
Could not use specialty as well

![Screenshot from 2021-01-22 19-20-16](https://user-images.githubusercontent.com/46927354/105517222-d2df9180-5ce7-11eb-811a-42d5b10c795b.png)

**Comment by mohammadmahboubeh** [comment]
It's manual install into ubuntu

**Comment by mohammadmahboubeh** [comment]
POST
	http://localhost/search_specialty
Status500
Internal Server Error
VersionHTTP/1.1
Transferred12.17 KB (11.14 KB size)
Referrer Policyno-referrer-when-downgrade

	
Cache-Control
	no-cache, private
Connection
	close
Content-Type
	application/json
Date
	Fri, 22 Jan 2021 16:44:26 GMT
Server
	Apache/2.4.41 (Ubuntu)
Set-Cookie
	XSRF-TOKEN=eyJpdiI6ImRBUExQbWdya3pQc2trcnBKdS9ITWc9PSIsInZhbHVlIjoiQUlQYmFsMUE0bnE5dWdvSE5UZ2pQbFo2NTNCRW95S1NiejJMWS9UZUc3Unhmb0MydXpJdDE0cnpTWmhFczM5QkdwUW1meVJrMVlSRm9Tb2JRcXp1ZmxITmJWb216WjVmaGVWRjcwU3dJaHpyeW4wRHdTMURYL3IwT2hudmNrWUQiLCJtYWMiOiJhY2RkNzQxZTRiYmVhYzk5NzYxNjFjNzhmMzcyYjY3YzYyZGMwMDRhNjE5YjZkNjQ5NWVkNzI2YzI0ZTFlMDNhIn0%3D; expires=Fri, 22-Jan-2021 18:44:27 GMT; Max-Age=7200; path=/
Set-Cookie
	laravel_session_nosh=eyJpdiI6Ino1ZEZveTd5TFB2QnNvMUducnJJTGc9PSIsInZhbHVlIjoiMmZtejQzY2V5MktYaDFKeHpRSXI3Zld4K21ETlNVSzRqM0Z3ejduTjloV24zK2ZtTEdKWHJqTk1iTDYzWG8wOFpmNG81WGh3bkh5VmNPT1Y3b0labDJ5R2pxa2tNSUEvQnpXOFdHbkxpdkVXWTJiL016YnE5ZjNIUlNrNWFsRUYiLCJtYWMiOiJiZjRkYmI2MjM0MWJiYmMyNjc3ODYzMmQzMGFlM2M4NjQwNzdlYzEwNzRmMGJkZDViZWZjM2Q1YTkyMzRjZTFmIn0%3D; expires=Fri, 22-Jan-2021 18:44:27 GMT; Max-Age=7200; path=/; httponly
Transfer-Encoding
	chunked
	
Accept
	application/json, text/javascript, */*; q=0.01
Accept-Encoding
	gzip, deflate
Accept-Language
	en-US,en;q=0.5
cache-control
	no-cache
Connection
	keep-alive
Content-Length
	20
Content-Type
	application/x-www-form-urlencoded; charset=UTF-8
Cookie
	laravel_session_nosh=eyJpdiI6InJCY3BKR3hPbmVmcW00bXp2YUVYdVE9PSIsInZhbHVlIjoiMzV6QmlaZEx2Q2s3NHc1TTZkRkEzT0s2dWJaWjZVaEMzTEp6L3YzWkZPUng5RWhiRDNUQkMxdUVUanhSazh6elcyRXpSZy83a0NYWG10NlFMeGFqa05qVGtQZUNBLzl0dDlwRFUrOUZ5ekcxVXl5VUJtRmZLMXFqd1Nkc3NhcXYiLCJtYWMiOiIyNjMzYzYyOGQ1ZDhlNmIwZDQ4YjBhN2NmYThkNTUxYjAwYTBjNzAwYjg2M2NhZmFhOWJlZWYzYzdjNDliY2E4In0%3D; XSRF-TOKEN=eyJpdiI6InNyc29UVnpWOURuWWlIa1BuWjI3NFE9PSIsInZhbHVlIjoiOWxzNGRNSHV0ejFYMjl5MVA1Zm1NNDRIRkY5NEQxNVhKTnJSaTlEL1NPRThRcWpUbW43OC9PUFpSeHp4dEZhalR3SStMMDRhL281NGJaa3F2eXFpYTl3RzJON3IvVy9UWW1tcWVqdDlMREFwTjhmek5yaFNEaHBXdnJyMS9UTGEiLCJtYWMiOiIxYzFiZmIyYjc3ZmM4MmY2NGE2OGU5NGI2MTE1MTI4NmI2NWQ0YWIyNDYwNmFiOGI0NDNkYWY3NzQxMWVlOGEyIn0%3D; nosh_tz=Asia%2FBaghdad
Host
	localhost
Origin
	http://localhost
Referer
	http://localhost/core_form/users/id/0/2
User-Agent
	Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0
X-CSRF-Token
	HLFpBFAJtLN58R2ZNCboXy9dwzjss7itrB40vPod
X-Requested-With
	XMLHttpRequest

**Comment by mohammadmahboubeh** [comment]
![11](https://user-images.githubusercontent.com/46927354/105606016-e6eac800-5da7-11eb-9ccf-829762a7304d.PNG)
