### ISSUE TITLE
install 

### ISSUE THREAD

**Issue by chrispecoraro** [shihjay2/nosh2#32]
When Login is clicked on new installation:
```
FatalThrowableError in InstallController.php line 94:
Type error: Too few arguments to function App\Http\Controllers\InstallController::install(), 1 passed and exactly 2 expected
```
Temporary workaround:
`    public function install(Request $request, $type = 'practice') `

**Comment by shihjay2** [comment]
Updated code to address missing route parameters for install.  See commit d41ffaebe7a1f9ff445d61b5fe6a24f93a5d1dcb
