### ISSUE TITLE
use needed in InstallController.php

### ISSUE THREAD

**Issue by chrispecoraro** [shihjay2/nosh2#33]
`use Illuminate\Support\Facades\Auth;` is needed in InstallController.php since
     Auth::attempt(['username' => $username, 'password' => $request->input('password'), 'active' => '1', 'practice_id' => '1']); resolves incorrectly.

**Comment by shihjay2** [comment]
Fixed in commit e7989bb8e76b2c5d36214b86b1afca147f70e4f0
