### ISSUE TITLE
Google client ID update error

### ISSUE THREAD

**Issue by rumsant** [shihjay2/nosh2#34]
After going to https://mynosh.org/nosh/google_start to update Google client ID, I get error after attempting to upload the JSON file:
"ErrorException in CoreController.php line 4991: imagesx() expects parameter 1 to be resource, boolean given"

**Comment by rumsant** [comment]
Discovered that this only happens if I'm logged into NOSH. After I log out and then go to /google_start it appears to work just fine.

**Comment by shihjay2** [comment]
Fixed misdirection of google upload in commit acf8261f6b28469ae3f899af7332acaf1c856574
