### ISSUE TITLE
"Setup" link from admin account failure

### ISSUE THREAD

**Issue by rumsant** [shihjay2/nosh2#36]
Clicking on the "Setup" link along the top of the page while logged into the admin account results in an error page that states: "ErrorException in CoreController.php line 5578: Undefined index:"

**Comment by rumsant** [comment]
The same error occurs when going to the "Configure>Practice Setup" link from a user account.

**Comment by shihjay2** [comment]
Fixed in commit acf8261f6b28469ae3f899af7332acaf1c856574 due to error handling of null values
