### ISSUE TITLE
"Setup" & "Configure>Practice Setup" link failure

### ISSUE THREAD

**Issue by rumsant** [shihjay2/nosh2#37]
Error is different from previous error, but still fails:
"ErrorException in CoreController.php line 5598: Undefined index: standardmedical"

**Comment by shihjay2** [comment]
Fixed in commit 7943f838daf4010cb02e80168c3313fa17ba2952

**Comment by rumsant** [comment]
I am still getting this same error after updating.

**Comment by shihjay2** [comment]
Fixed in commit 5058efcbaebdf43c92a47d76cf0bff58f4232546

**Comment by rumsant** [comment]
Similar error with different code:
"ErrorException in CoreController.php line 5622:
Undefined index:"
