### ISSUE TITLE
Patient>Demographics>Contacts>"Test Reminder" link failure

### ISSUE THREAD

**Issue by rumsant** [shihjay2/nosh2#38]
Returns "No Reminder Method Set" message even when reminder has been set.

**Comment by shihjay2** [comment]
When reminder is set, was the save button clicked prior to clicking on the Test Reminder link?  The logic is that the info must be saved first; I can try to see if I can have the info saved before running the test.

**Comment by rumsant** [comment]
The save button was clicked prior to clicking on the Test Reminder link.

**Comment by rumsant** [comment]
Unless there is some setting for this under the "Practice Setup" area that I have not configured yet due to not being able to access it at the moment due to error.

**Comment by shihjay2** [comment]
Fixed in commit f4959bacdd651a7357e7db92e13870538235a9a9
