### ISSUE TITLE
"Dropdown List" for template group item

### ISSUE THREAD

**Issue by rumsant** [shihjay2/nosh2#40]
When trying to add an item to a template group, the dropdown list feature does
not appear properly (at all) after creating the item.

**Comment by rumsant** [comment]
Correction: It does appear as long as the delimiter is set to "new line".
It wasn't working with delimiter set to "space".

**Comment by shihjay2** [comment]
Not able to replicate this bug.  When you create the items in the dropdown list, are they all appearing?  Also when you mention about the delimiter, that's when the items selected in the template area are copied to the text box; are you referring the copied text or the dropdown box itself?

**Comment by rumsant** [comment]
If the delimiter is set as "space" while I try to create a dropdown list (or checkbox item) the dropdown list (or checkboxes) will not appear in the item once it is saved. The title of the item will appear, but not the options.

If "new line" or even "double space" is selected while creating the item, it appears to work just fine. Not really a big deal, I suppose, but it confused me for a moment.

**Comment by shihjay2** [comment]
Just curious, what browser are you using?  I'm wondering about how javascript is not functioning as expected.

**Comment by rumsant** [comment]
I switched over to Chrome to make sure that my heavily modified Firefox wouldn't cause issues.

**Comment by shihjay2** [comment]
I've been looking through the code and I can't seem to see how setting the delimiter would change the behavior of how the templates are saved or not specifically for dropdowns, checkboxes, and radio buttons.  I'll keep checking; again, I'm not able to replicate this behavior and may commit 2c17bb81e5a7b41c0623d24981f17f9005db0613 would have fixed it?

**Comment by rumsant** [comment]
I will recheck it later this evening when I have a chance. It did seem like a strange behavior between two things that really shouldn't be related as far as I can tell. I'll see if I can replicate again report back.
