### ISSUE TITLE
Exam preview

### ISSUE THREAD

**Issue by rumsant** [shihjay2/nosh2#41]
The exam preview feature does not appear to be including any saved information from the Objective Physical Exam text entry box.

**Comment by shihjay2** [comment]
I figured out what all these multiple errors are coming from; it looks like you migrated from the old version of NOSH but did not set any required settings, migrated to NOSH 2.0 without those required settings and the system was assuming it was a preset practice thinking they were set and currently nothing is working correctly right now.  That includes the physical exam not showing up in the preview (it is actually saved) but the old default template (standardmedical) has been retired and should have migrated (but it didn't). I'm updating the code to catch this and you need to go back to setup and fill out the mandatory settings that didn't get set.  I'll let you know when an update is ready.

**Comment by rumsant** [comment]
I see. I thought that doing a vagrant destroy would get rid of everything. Does vagrant destroy leave the /noshdocuments or database in the virtual machine intact?

**Comment by rumsant** [comment]
And would it be best if I were to do a complete reset at this point to ensure that I'm not coming up with self-inflicted bugs? If so, how is that best done?

**Comment by shihjay2** [comment]
Vagrant destroy should have removed the entire machine (database, noshdocuments) - are you sure you're not working on the vagrant machine or on a local machine - you mentioned you managed to install nosh-cs which was the old version of NOSH and you migrated that to NOSH 2.0 besides, all current Vagrant code is installing NOSH 2.0 right now so I don't Vagrant is the issue.

**Comment by shihjay2** [comment]
No need to completely reset, once I get this updated code that catches all possible scenarios (like what you encountered), it should correct itself.  You never know how NOSH is used so it's always best to build and improve code on worst-case scenarios.

**Comment by rumsant** [comment]
Yes, I'm definitely running on virtualbox. Tbh though, I've done so many installs and reinstalls, perhaps I'm misremembering when I last did a vagrant destroy on this computer.

I'll hold up and wait for the update.

**Comment by shihjay2** [comment]
Updated NOSH with commit 2c17bb81e5a7b41c0623d24981f17f9005db0613

**Comment by rumsant** [comment]
I am current with update_system, but I am still missing the Physical Exam text from the encounter preview and review screens.

**Comment by shihjay2** [comment]
Fixed in commit 3583d11880efeae5de6a43cfe460e8146e895b01
