### ISSUE TITLE
ambiguous redirect

### ISSUE THREAD

**Issue by rumsant** [shihjay2/nosh2#43]
After successfully obtaining a certificate with letsencrypt there is a message in the terminal stating: "/vagrant/ssl.sh: line 92: $LOG: ambiguous redirect".

After this happens I can no longer get to /nosh. Instead I get a message in the browser that states: "The 192.168.1.150 page isn’t working - 192.168.1.150 redirected you too many times. - Try clearing your cookies. - ERR_TOO_MANY_REDIRECTS"

After clearing cookies I can get to the login page, but after trying to login it takes me a browser page with the same error as above.

Before getting the certificate I can navigate to /nosh just fine, so I assume these two events are related.
![ambiguousredirect](https://cloud.githubusercontent.com/assets/26801488/24576851/a33dbb18-166f-11e7-8c91-0d92d5ab4fa2.png)

**Comment by shihjay2** [comment]
This issue was moved to shihjay2/nosh-in-a-box#3
