### ISSUE TITLE
Provision for allowing access outside of LAN

### ISSUE THREAD

**Issue by rumsant** [shihjay2/nosh2#44]
The recently added provision to allow access from outside of LAN does not work for me. Enabling it gives me a "route -n" readout that looks like the following:
![stockprovision](https://cloud.githubusercontent.com/assets/26801488/24576863/ec143542-166f-11e7-84fd-4bc642fded5b.png)

Using an alternate provision as follows does work:
  config.vm.network "public_network"
  config.vm.provision "shell", run: "always", inline: "route del default; route add default gw 192.168.1.1"

The "route -n" readout using this alternate provision looks like the following:
![workingprovision](https://cloud.githubusercontent.com/assets/26801488/24576886/4ff93698-1670-11e7-949d-9b283f4cd53b.png)

As you can see there is a difference between the two, and even though I don't know what I'm doing, I'm assuming that the difference lies in the deletion of the default route prior to specifying the proper default gateway to use.

**Comment by shihjay2** [comment]
This issue was moved to shihjay2/nosh-in-a-box#4
