### ISSUE TITLE
Patient ID

### ISSUE THREAD

**Issue by rumsant** [shihjay2/nosh2#47]
I see that patients are assigned an ID based on order of entry into the system.

In the event that someone wants to migrate into Nosh, it would be helpful to either be able to manually set the ID of the patient, or have a field in the demographics section to record something like a file number.

edit: this was supposed to be submitted as a suggestion, but it looks like it went in as an issue.

**Comment by agropper** [comment]
I agree that patients should be able to provide an identifier or authorization server to be used for health information exchange.

**Comment by shihjay2** [comment]
Added Patient ID field in Demographics -> Name and Identity, in commit b4f7dee830dcbd6e7b2ecf7a8ba105dfc83db697
