### ISSUE TITLE
Editing user created form

### ISSUE THREAD

**Issue by rumsant** [shihjay2/nosh2#48]
While editing a user created form, when trying to delete a previously saved field, the following error occures:
"ErrorException in CoreController.php line 1232:
Undefined variable: message"

**Comment by shihjay2** [comment]
Fixed in commit b4f7dee830dcbd6e7b2ecf7a8ba105dfc83db697

**Comment by rumsant** [comment]
With this update I was able to delete 1 text field. When I tried to delete a second text field, I was told that the field was successfully removed, but it did not disappear as the previous one had.
I tried to save the modified form despite the fact that the second text field hadn't been deleted, but it could not allow me to save the form. Instead a pop-up message told me to fill out the field that I had attempted to delete.

Additionally, when I attempted to delete a radio button field, I was take to an error page as follows:
"This 192.168.1.121 page can’t be found
No webpage was found for the web address: https://192.168.1.121/nosh/configure_form_remove//2
HTTP ERROR 404"

**Comment by shihjay2** [comment]
This behavior seems to be related to some erroneous sessions handling (it's related to another error you had posted regarding billing).  I'm looking into it but I can't replicate this issue on other systems.

**Comment by shihjay2** [comment]
I'm beginning to suspect this is related to Vagrant implementations and file permissions (specifically with sessions handling).  I'll be posting a fix once I figure out what is going on.

**Comment by shihjay2** [comment]
in Vagrantfile can you substitute
config.vm.synced_folder "", "/vagrant"
for
config.vm.synced_folder "", "/vagrant", :mount_options => ["dmode=777","fmode=666"]

reload Vagrant and see if you're still having the same issues.

**Comment by rumsant** [comment]
The change to the vagrant file did not seem to change this problem.

**Comment by shihjay2** [comment]
Fixed in commit d19ef10e68f175f894d703555b95f29ae91a5f4a

**Comment by rumsant** [comment]
With this update it appears that I am able to delete the items. However, when I attempt to save the form after deleting an item, I get the following error:
"MethodNotAllowedHttpException in RouteCollection.php line 218:"

That being said, if I then cancel out of the form after trying to save it and getting the error message, returning to the form shows that it has indeed been saved.

**Comment by shihjay2** [comment]
Fixed in commit f8533297a869e92e23f36b31b8462ac8a0f3a3bc

**Comment by rumsant** [comment]
Update changed behavior a little, but there is still some strange behavior that is difficult to narrow down, so I am going to give an example of what I'm observing:

1. Create a new form.
2. Add 2 text fields and 2 radio fields.
3. Save form. (Here I am told I need to fill out the text fields. It will not allow me to save)
4. Cancel out of form creation because I am unable to save.
5. New form is present in forms list and clicking on it brings up the form with 2 text fields and 2 radio buttons (it did actually save).
6. Attempt to edit a radio field (this works fine).
7. Attempt to edit a text field (taken to an error page with the following error: "ErrorException in CoreController.php line 1040:
Undefined variable: form_options"
8. Delete one of the two radio fields (this works fine).
9. Delete one of the two text fields (this works fine).
10. At this point it gets difficult to keep track of what's really going on because if I add back another radio and text field, and then try to delete another field, it deletes a different field than the one I selected for deletion.

**Comment by shihjay2** [comment]
Fixed error #7 with commit c158b1b3f8f43b288fc2a0fd602fdf1a7146f173

**Comment by rumsant** [comment]
I can confirm that #7 appears to be fixed.

**Comment by shihjay2** [comment]
I believe I have addressed the problem when a form item is deleted in the middle of the form and item indexes are no longer being tracked properly.  Fixed in commit 09e7cdf83fcdd2cd18de1bb88a842848a9e71b1f

**Comment by rumsant** [comment]
That does appear to be fixed now as far as I can tell.

Also, perhaps it would be a good idea to have an option to delete a form.

**Comment by shihjay2** [comment]
Added ability to delete a form in commit f3554b7cf7fa84858f7d3c2d657ee3a7d9d9371d
