### ISSUE TITLE
New encounter>Associated appointment

### ISSUE THREAD

**Issue by rumsant** [shihjay2/nosh2#49]
I am unclear as to what the "associated appointment" field is for when setting up a new encounter, but I do not have any options when clicking on the dropdown menu. It only says "no appointment".

I'm assuming that perhaps this is used to associate the encounter with an appointment on the schedule, so I've made sure that there is an appointment on the schedule for the patients, but I still don't see any options in the "associated appointment" field.

This may be a misunderstanding on my part as the to function of this field.

**Comment by shihjay2** [comment]
You're right; apparently it only works when you change the provider but if you're the default - the search call for appointments never gets triggered.  Fixed in commit 004f71a8adc978ade2930552778d8ea10da1965c

**Comment by rumsant** [comment]
Okay. That works.
