### ISSUE TITLE
Suggestion: Schedule>Appointment>New Encounter option

### ISSUE THREAD

**Issue by rumsant** [shihjay2/nosh2#50]
When you create a new encounter, you associate it with an appointment on the schedule.

Would it be an efficiency optimizer to be able to click on an appointment on the schedule and have an option to directly create a new encounter for the patient to whom the appointment is assigned?

I suppose it depends on your practice setup and workflow, but in some cases it make reduce the amount of clicks necessary.

**Comment by shihjay2** [comment]
Added in commit b5089ea8385cec0ba7ffd7c161683e3fefa2402b

**Comment by shihjay2** [comment]
Look for Encounter bottom in the dialog box - it'll open the associated encounter if it's already created and not signed; you'll be able to view and not in edit mode when it's signed.  It'll create the encounter with default parameters (using reason as chief complaint, default place of service, provider based on schedule) and take directly to the encounter page.

**Comment by rumsant** [comment]
Nice.
