### ISSUE TITLE
New Encounter>Associated Appointment potential issue

### ISSUE THREAD

**Issue by rumsant** [shihjay2/nosh2#53]
When creating a new appointment, the choices available for Associated Appointment appear to include all past appointments.

Is this be design? Are there situations where you would be entering a new encounter for an appointment that has already been completed on a previous day?

If a patient accumulates a long history of visits, the practitioner would need to scroll to the bottom of the dropdown list for Associated Appointment in order to find the visit for the current day.

**Comment by shihjay2** [comment]
The list of appointments only span 1 week before and after the date the encounter is opened (like today) so it's not going to be a long scroll.

**Comment by rumsant** [comment]
Got it.
