### ISSUE TITLE
SMS reminders

### ISSUE THREAD

**Issue by rumsant** [shihjay2/nosh2#54]
I don't know if SMS reminders are supposed to work right out of the box, or if there is an additional service that needs to be set up. If the are supposed to work automatically, they do not appear to be working.

**Comment by shihjay2** [comment]
It looks like the service (textbelt) is no longer free so it's not working right now.  I'll let you know if there is a replacement feature.

**Comment by rumsant** [comment]
I don't know if this would be helpful or not, but just in case, allow me to explain how I've implemented SMS text reminders in the past without paying for a service. It's not as efficient as it could be, but who knows, maybe you could make it automate into your system.

1. Google form with 4 fields: SMS Number, Appointment Date, Appointment Time, Send Time (how long before the appointment the patient would like to receive the reminder in hours, days, etc.)

2. The submitted form entry creates a new row in a Google Spreadsheet document.

3. When a new entry in that Google Spreadsheet is created, a Zapier recipe automatically creates a Google Calendar event populated with the data from the form:
--Event Title/Summary=SMS Number from form
--Event Start Date & Time=Appointment Date & Appointment Time from form MINUS the Send Time on the form (-1d, -2h, etc)
--Event End Date & Time=Appointment Date & Time from form
--Lastly, a unique string of characters is added to the Event Description.

4. IFTTT monitors the Google Calendar for which Zapier creates events. Whenever it encounters an event with the unique string of characters in the Event Description field, it sends a text message from the office mobile phone to the SMS number in the Event Title. The text message is preset in the IFTTT recipe to whatever you want, such as "Reminder for your appointment with Dr. Blank on <Appointment Date> at Appointment Time>."

All of this happens in the background without any effort. This system is a tad cumbersome as you need to copy/paste the SMS number into the Google Form, use the date picker widget to pick the appointment date and enter the time and then type -1d (send one day before the appointment) or -3h (send 3 hours before the appointment), etc. But with the right kind of system that could all be automated.

It may or may not be useful to you, but I thought I'd share it.

**Comment by shihjay2** [comment]
Updated in commit 939f5c53e06b3c93b5f241233b46d2421a834b23

**Comment by rumsant** [comment]
Looks like the same error is occurring.

**Comment by shihjay2** [comment]
What is the error message that you get?  You can do a test run by going to Demographics, set patient with a mobile number and change reminder method to Celluar Phone.  Save and then click on Test Reminder.

**Comment by rumsant** [comment]
Sorry, I was not being attentive and I thought this was the CCDA thread. I will check it out now.

**Comment by rumsant** [comment]
SMS appears to work.
I looked into textbelt a little bit. How do you have this working without a funding source?

**Comment by shihjay2** [comment]
Before it stopped working, Textbelt was a free service and it had an API where NOSH made a request and it would send an email-to-sms message; but then it changed recently where you needed an API key and now you have to pay to get the API.  Textbelt is an open source project on GitHub, so this morning, I  installed on my cloud server and so all NOSH installs will make a call to the new URL instead of the txt.textbelt.com URL and it uses my noshchartingsystem@gmail.com account to send messages without any charge.  The way textbelt works is it blasts email to all known US mobile carriers and hopefully one of them is correct - it doesn't ask which mobile service the number is associated.  An older version of NOSH required that you knew which carrier the number is associated but it was cumbersome and when patients switch carriers, which happens a lot, then the SMS would stop working. At least with textbelt, I don't have to set the carrier.

**Comment by rumsant** [comment]
So as long as the carrier has an SMS gateway, the text should go through, correct?

It looks like the email-to-sms version of textbelt is still open-source. The paid version doesn't use the email-to-sms gateway--apparently they have contracted with the carriers to be able to provide the sms in a different fashion.

**Comment by shihjay2** [comment]
Yes.

**Comment by rumsant** [comment]
I am wondering what is the schedule for appointment reminders? I am assuming that if they are enabled, they are sent automatically for all appointments. When are they sent relative to the appointment start time?

**Comment by shihjay2** [comment]
When an appointment is added and it's after today, a notification is sent.
When an appointment is changed and it's after today, a notification is sent.
If it is 48 hours before the appointment, a notification is sent.
Notification only occurs if there is a set reminder method for a patient.
