### ISSUE TITLE
Export>Entire Database stalls

### ISSUE THREAD

**Issue by rumsant** [shihjay2/nosh2#55]
I am not able to export the mysql database. The progress bar never advances.

**Comment by shihjay2** [comment]
Fixed on commit f7c3546a096ef34de773110c7db04da805c6668e

**Comment by rumsant** [comment]
I am able to download the sql, but I just noticed that whenever I log in to the admin account, it logs in with a grayed out window with the "creating database"  window working.

It doesn't appear to actually create the database, and I can click on the screen and it disappears.

**Comment by shihjay2** [comment]
Fixed in commit da2cf075a1b97f340627ebe1a9d9862ac711dfe2

**Comment by shihjay2** [comment]
You'll to let it run one time (and it'll show the dialog) but then it should not pop up again.
