### ISSUE TITLE
CCDA export

### ISSUE THREAD

**Issue by rumsant** [shihjay2/nosh2#56]
The CCDA export never completes and nothing is downloaded.

**Comment by shihjay2** [comment]
Is this from admin or from the chart?

**Comment by rumsant** [comment]
admin

**Comment by shihjay2** [comment]
If you can open up a developer console window (from Chrome it's Ctrl-Shift-I), click on Network in the panel and run the command again - click on the line that's red (it's an error) and click on Preview to show the error page and screenshot it for me.

**Comment by rumsant** [comment]
![1](https://cloud.githubusercontent.com/assets/26801488/24689338/44061c70-1972-11e7-81f9-4744bb76ba77.jpg)

Does this look correct?

**Comment by shihjay2** [comment]
Sorry, click on Response instead of Preview (it's hard to read the HTML when it's that small)

**Comment by shihjay2** [comment]
Come to think of it, the error doesn't seem to be coming from NOSH - the HTML is not recognizable and I checked and normally Preview will show a webpage response; there should be an item on the left hand side called download_ccda_entire - that's the one that is stalling.

**Comment by rumsant** [comment]
I did the wrong thing. Sorry. I'll get the correct screenshot.

**Comment by rumsant** [comment]
![response-01-01](https://cloud.githubusercontent.com/assets/26801488/24689702/cf8a5264-1974-11e7-9574-9f6d05f67e95.jpg)

Well, this should be the screenshot you're asking for, but I think it looks the same as the previous.

There is a download_ccda_entire on the left at the top, but it's not in red and the response tab for it just says "Failed to load response data".

**Comment by rumsant** [comment]
The error line "1491366423_1_track" doesn't turn red immediately. Only after a few seconds it turns red after the lines below have loaded.

**Comment by rumsant** [comment]
[track preview.txt](https://github.com/shihjay2/nosh2/files/900227/track.preview.txt)

**Comment by shihjay2** [comment]
It looks like there was format recognition issue when NOSH is looking for an ICD10 code in one or more of your entries in Problem List.  If you didn't pull in an issue from the search bar with the format Diagnosis DEscription [xxx.xx]; that's why the error is occurring.  I've updated the code to be more fault tolerant in commit 52a03384059d382242ee83be069ffa6dbbed5685

**Comment by rumsant** [comment]
I must apologize. I was trying to figure out how everything worked, and I wanted to see if I could manually add a diagnosis code to the database and have it show up in the program.

I will remove that addition and refrain from screwing around with things so that my bug reporting isn't inaccurate.

By the way, what is the difference between a Dx code that shows up green vs. red?

**Comment by rumsant** [comment]
The CCDA does download now.

**Comment by shihjay2** [comment]
Green is a billable code; when you click on a Red code it will expand that code (the expanded ones are blue) which you can use; Red is a code that is not specific enough for billing purposes.
