### ISSUE TITLE
Add Supplement for patient

### ISSUE THREAD

**Issue by rumsant** [shihjay2/nosh2#57]
When adding a supplement for a patient, if you leave the "Action after saving"
as "Do Nothing", a tooltip comes up telling you to "Please select an item from
the list" and it does not allow you to save.

**Comment by shihjay2** [comment]
Fixed in commit 1dfa2f1c6be3abaee46a80cbee2fbdc3fbfa7912

**Comment by rumsant** [comment]
Tried to update, but got this error:
"RuntimeException in HttpClient.php line 150:
You have reached GitHub hour limit! Actual limit is: 60"

What's that all about?

**Comment by shihjay2** [comment]
Sounds like you ran into a hiccup on the Github server.  Can you try the update again; just to be safe, do it in about 1 hour so that you don't get hit with the time limit.  I just tried the update on a different server and it worked fine.
