### ISSUE TITLE
User invitation expired>duplicate email address

### ISSUE THREAD

**Issue by rumsant** [shihjay2/nosh2#59]
Created a user from the admin account.
Wasn't able to follow the email link to set up a username
and password until a couple days later.
The invitation link had expired, and the user disappeared
from the admin account.
When I tried to re-enter the user, I wasn't able to use the
email address again because I was told that the email
address had already been taken, even though the user
had disappeared.

**Comment by shihjay2** [comment]
Removed expiration in commit 8ac20a65f8647d410e9fe24d69bbfc35703363e3
