### ISSUE TITLE
SMS Reminder Question

### ISSUE THREAD

**Issue by rumsant** [shihjay2/nosh2#61]
Wondering if the content of the SMS reminder can be changed.

I found the file where you can edit the main message: "Reminder - medical appointment with......"

But in the SMS reminder there is also the "FRM:NOSH Charting ChartingSystem", and "SUBJ:txt" pieces of the SMS message, and I wasn't sure if those could be changed or if they are a result of the way the textbelt service is set up.

Also, while the message does come as a single SMS, it includes text that seems to indicate that it is coming in two parts, beginning with "1 of 2", and then before the end of the message it splits and inserts "(Con't) 2 of 2" before continuing with the end of the message. Again, perhaps this is just an unavoidable part of the way the service runs, but I was curious.

**Comment by shihjay2** [comment]
Unfortunately, it can't be changed since it is coming from the unified service and since it is coming from one e-mail address - changing the FROM address will cause an error with matching to the originating email address - SMS from email is restrictive.

**Comment by rumsant** [comment]
Okay, I thought that might be the case. I was just a little confused because when I was reading through that link you gave me regarding the setting up of a self-hosted textbelt server, it didn't say anything about a particular email address being used as the sending email address.

It mentioned that "Some carriers may deliver text messages from txt@textbelt.com while others will simply show “Root” as the SMS sender." I assumed this meant that everything was handled by the textbelt service, but you must have it set up a little different than the way it was explained in that post. Correct?

**Comment by shihjay2** [comment]
In the link I gave you, it says you need to set up an IMAP e-mail relay (mutt package) on the server that the textbelt service is running on and you have set the username and password for that account where the email is originating from.  The main configuration is set to the noshchartingsystem@gmail.com account for the unified service (previously it was on someone else's server whose email was txt@textbelt.com) in my instance.  If you're using Gmail you need to make sure you have turned on IMAP for that account and to allow less secure methods of login which is a google accounts setting.
