### ISSUE TITLE
Anatomical images

### ISSUE THREAD

**Issue by rumsant** [shihjay2/nosh2#62]
If I try to add a  preset anatomical image to an encounter, the image does not load.

I've done this before on a prior installation and it seems to load and work fine, but currently I'm not seeing any image appear after selecting a preset image.

**Comment by shihjay2** [comment]
Cannot replicate.   Do you have any screenshots including the console?  Were there any permissions or file system changes that took place?

**Comment by rumsant** [comment]
I don't believe I changed anything, but I did notice that I am getting a notice when I vagrant up or vagrant ssh. I haven't seen this notice before, and I'm not sure why it's happening now:

"/opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/util/platform.rb:24: warning: Insecure world writable dir /home/office01 in PATH, mode 040777"

Maybe this has something to do with it?

**Comment by rumsant** [comment]
Here is the console image.
![console-01](https://cloud.githubusercontent.com/assets/26801488/25111122/9518e8b8-2395-11e7-896a-7cb559b36d2c.jpg)

**Comment by rumsant** [comment]
If you're wondering about the address, it's just because I have my hosts file set up so that nosh.com is NOSH's local IP address.

**Comment by shihjay2** [comment]
Do you have /noshdocuments in a different machine?  It looks like it's trying to reference /home/office01 and the permissions of that directory are preventing vagrant from making it public which is what is causing the image not to load.  The error is showing that NOSH cannot pull the file.

**Comment by rumsant** [comment]
office01 is the host computer, but /noshdocuments is where it should be in the virtual machine.

Everything else seems to be working well and normally.

The only thing I can think of is that I screwed something up when I was figuring out now to get the textbelt server running, but I don't think that's the case.

If that is the case, I may just have to reinstall.

**Comment by shihjay2** [comment]
It's a permissions issue of some sort.  

In /noshdocuments/nosh2/public/assets/images/illustrations here will be a f and m folders.  They all need to be 777 permissions (-rwxrwxrwx when you ls -l in each directory) and there should be files in each one.  Owner needs to be www-data.

**Comment by rumsant** [comment]
If I attempt "sudo chmod 777 /noshdocuments/nosh2/public/assets/images/illustrations/m" it doesn't change the permissions and I'm not sure why.

Also, it looks like that directory string is set to "drwxrwxrwx" all the way from the "public" folder.

**Comment by rumsant** [comment]
Well, I don't like this, so I'm going to reinstall to make sure I didn't screw something up.

**Comment by rumsant** [comment]
I did a vagrant destroy and reinstalled, and I'm still getting the same issue and the same folder permissions are still messed up.

Could this have anything to do with this message that I am getting during the initial install:

"[default] GuestAdditions versions on your host (5.1.18) and guest (5.0.32) do not match."

**Comment by shihjay2** [comment]
That is possible.  The guest additions handles the root directory permissions which will include /noshdocuments so it could be setting permissions wrong.

**Comment by rumsant** [comment]
I'm just not sure what it means that the host guest additions don't match the guest. Is the guest running virtualbox too? Do I need to try installing an earlier version of virtualbox on my host so that I can match the guest additions to the guest?

**Comment by shihjay2** [comment]
Did you run this command as explained by the wiki `vagrant plugin install vagrant-vbguest` before you `vagrant up`; if you did, it should check and make sure your guest additions match and if it doesn't it should update it accordingly.

**Comment by rumsant** [comment]
I did. And it appeared to update them, but for some reason these permissions are apparently wrong on folders for the anatomical images, so I figured it might have something to do with the guest additions. 
Perhaps it's something else that's causing the problem.

**Comment by shihjay2** [comment]
I'm going to point you to this link; it's related to whatever permissions you set where the Vagrant installation is happening.   http://stackoverflow.com/questions/6192003/insecure-world-writable-dir-users-username-in-path-mode-040777-when-running-ru; you might want to Google "error vagrant insecure world writable" as well.

**Comment by rumsant** [comment]
Finally had some time to look at this again.

First of all, the whole "insecure world writable" thing turns out to just be a result of having shared my home folder on the host with the other computers on my LAN.

Secondly, the guest additions problem is apparently a Virtualbox 5.1.20 problem. I downgraded to 5.1.18 and that has gone away.

Lastly, it turns out that the whole anatomical images debacle is the result of my using the hosts file on my computers to assign the NOSH IP address to www.nosh.com (I did this so that I could create a google credential w/out directing an actual domain to my public IP because you can't use an IP address to create a google credential). It turns out that I never thought about changing the hosts file on the virtual machine, and when I stared at the console long enough I realized this was the issue.

Sorry about that.
