### ISSUE TITLE
Test SMS Reminder

### ISSUE THREAD

**Issue by rumsant** [shihjay2/nosh2#63]
I was testing out the new option to input the address of your own textbelt server, and realized that the "Test Reminder" for SMS messages doesn't seem to be working.

Whether I am using the default textbelt server or my own doesn't seem to matter--no banner pops up confirming that a message was sent, and no message is received.

SMS reminders do go out appropriately for events, the only thing not working is the "Test Reminder" button in Demographics>Contacts.

**Comment by shihjay2** [comment]
Fixed in commit cebc318c1d4ec7f1c3db1073b11b068dce121d5c
