### ISSUE TITLE
Suggestion>CPT code Favorites

### ISSUE THREAD

**Issue by rumsant** [shihjay2/nosh2#65]
When selecting a CPT code for the first time, a banner appears asking if you would like to add the code to your Practice and another asking if you would like to add it to your Favorites.

I am not sure what adding it to the Practice does, but I understand that adding it to Favorites makes it easily accessible via the "Star" icon for future use.

My problem is that I clicked on "Add to Practice" and the "Add to Favorites"  option then disappeared. Now I am unable to bring up the option to add that CPT code to my Favorites anymore, but I would like to do that.

My suggestion would be to have a way to add a CPT code to Favorites if you failed to do so the first time you searched for that code (unless, of course, there is a way to do this that I am not aware of).

**Comment by shihjay2** [comment]
Fixed in commit b9bc7a4924f75bcf229ddd892e0de8a1091c1743 where once you click Add to Practice, the option will not show up in the future to Add to Favorites.  Now when you're presented with both options, clicking Add to Favorites will add the CPT to the practice AND add it as a Favorite.
