### ISSUE TITLE
Suggestion>Schedule>Appointment status

### ISSUE THREAD

**Issue by rumsant** [shihjay2/nosh2#67]
Mousing over an appointment brings up a box that shows the "Reason" and "Status"  of a given appointment.

I believe that it would be useful to be able to look at a current day's schedule and visually assess the "Status" of appointments without having to mouse-over each one individually.

For example, if one wanted to look quickly to see which appointments had been canceled/missed, a visual indicator would give that information more quickly than mousing over individual appointments.

It could be something as simple as having one of the corners or ends of the appointment box colored to represent the "Status" of the appointment as it currently stands.

**Comment by shihjay2** [comment]
Added feature i commit 5cfd073493ad6f43e34779fc9e3e52f9311bbc19

The border of an appointment will be green for attended status, black for DNKA, red for LMC as indicated in the legend on the left (or top in mobile).
