### ISSUE TITLE
Editing Patient Name

### ISSUE THREAD

**Issue by rumsant** [shihjay2/nosh2#68]
I recently added a new patient and mistakenly used one "t" in their name when it should have been two.

As far as I can tell there is no way to edit the original name entry for a patient. Editing the demographics does not appear to update the patient name as it is used for scheduling and in a few other areas.

It would be useful to be able to change this (unless it's already there and I'm just not finding it).

**Comment by shihjay2** [comment]
I believe it is now fixed and updates schedule in commit beb8873ed59d451a3d2f175081ff085238e11d28.  Let me know if you find other areas were it is not updating.  You may need to go to Demographics -> Edit in Identity and Save again to make changes to the schedule after updating.

**Comment by rumsant** [comment]
Looks like that did it. Thank you.
