### ISSUE TITLE
Make Addendum (don't do it)

### ISSUE THREAD

**Issue by rumsant** [shihjay2/nosh2#78]
When I attempted to make an addendum to a signed encounter today, I clicked on the "Make Addendum" button and an error page popped up.

After I backed out of the error page, I discovered that the signed encounter was no longer signed, and all of the information within it had disappear, leaving me with an empty, unsigned encounter.

I then discovered that I can no longer search for that patient and go to his profile directly. If I click on his name in the patient search bar I am taken to an error page that begins with the following header:
"1/1 ErrorException in Controller.php line 15450:
Undefined variable: title"

The only way I can find to access that patient's profile is by clicking on "Encounters to Complete" from the home screen, which then takes me to the encounter that was unsigned and cleared after trying to make an addendum.

From there I can access the patient's Demographics and other information, but it I click on the patients name at the top of the left sidebar (above the green "Active Encounter: #") then I am taken to the same error page mentioned above.

**Comment by shihjay2** [comment]
You actually uncovered 2 issues, one was related to making an addendum; the second was a missing identifier for Surgical History for the timeline generation which resulted in the undefined title variable error.  Both are fixed in commt 14ddf903b7ecb4c2ef8925e66a24e875e2318180
