### ISSUE TITLE
Online Demo

### ISSUE THREAD

**Issue by WealthCity** [shihjay2/nosh2#79]
Do u have an online demo of the app..??

**Comment by shihjay2** [comment]
Yes, it's at http://demo.noshchartingsystem.com:444/nosh

**Comment by WealthCity** [comment]
user credentials

**Comment by shihjay2** [comment]
Provider User Level Login: demo_provider
Assistant User Level Login: demo_assistant
Billing User Level Login: demo_billing
Patient Portal user: demo_patient
Password (for all accounts): demo
