### ISSUE TITLE
Appointment reminder timing

### ISSUE THREAD

**Issue by rumsant** [shihjay2/nosh2#80]
This is not so much an issue as it is a question. I hope it's okay that I post it here.

I'm assuming that it would be fairly simple to change the timing of when reminders are sent out. For example, it would be much more effective if I could have reminders sent out 24 hours prior to the appointment rather than 48 hours.

Would this involve changing something in "/app/Http/Controllers/ReminderController.php"?

I'm apprehensive to just go mucking about because I don't know exactly what to change and if there are other dependencies that will need to be changed as well.

Additionally, this is probably not worth the time and effort, but I'll throw it out there anyway: An option in a patient's Nosh file next to "Appointment reminder method" that allows you to set individually how long before an appointment the reminders will be sent out. Something like "-3h" or "-1d" for 3 hours before or one day before, respectively.

For patients at the low end of the bell curve, sending an appointment reminder 48 hours before an appointment is pretty much equivalent to sending it 48 days before the appointment.

Thanks.

**Comment by shihjay2** [comment]
Yes, the setting is in ReminderController.php - line 21 where it starts with
<code>$end = time() + (2 * 24 * 60 * 60);</code>

Remove the 2 * and that'll get you to 24 hours prior.

I'll look into having reminders individually set in some future update.

**Comment by shihjay2** [comment]
Added ability to customize reminder intervals both practice-wide and patient-specific in commit 9a997b90782c7a8b45441a71a5a09386f79a018b

**Comment by rumsant** [comment]
Nice!
