### ISSUE TITLE
How to setup OIDC?

### ISSUE THREAD

**Issue by ajinkyagadewar** [shihjay2/nosh2#82]
Hello:

How can we setup on our own server? How can we setup site like http://noshchartingsystem.com/oidc/

Thanks.

**Comment by shihjay2** [comment]
http://noshchartingsystem.com/oidc/ is a demonstration site that is modified version of [HIE of One Authorization Server](https://github.com/shihjay2/hieofone-as).  The modifiecations are not reflected in the code there (some are cosmetic but others show functionality such has showing FHIR data, FHIR transactions which are not in the HIE of One code).  The role for the demonstration site is to show what an institutional EHR can do to obtain and view FHIR data from a patient centric EHR such as NOSH (when installed as a patient centric EHR, not as a physician centric EHR).

**Comment by ajinkyagadewar** [comment]
Good to hear that Sir. I would like to setup similar server. Can you please help me with that? I have already setup OpenID Connect server with Mitre but I need it to work with all end points like the way you have setup Nosh EMR and Nosh charting system. 

Thanks.

**Comment by ajinkyagadewar** [comment]
Can you please help me setting us system like noshchartingsystem.com/oidc? I have already setup OpenID Connect server with Mitre but I need it to work with all end points like the way you have setup Nosh EMR and Nosh charting system.

**Comment by shihjay2** [comment]
If you are using Mitre OIDC I would refer to their documentation regarding setting up clients dynamically and manually.  Like I mentioned before the link you are referring to is a heavily modified version of HIE of One AS which is its own OIDC server and client.  Instructions for setting up clients dynamically is in the readme of the HIE of One AS GitHub site.

**Comment by ajinkyagadewar** [comment]
Oh okay. I thought even that code is open source and will be available in any of the repositories. Thanks for the clarification.
