### ISSUE TITLE
"Are you new to the patient portal"?

### ISSUE THREAD

**Issue by ajinkyagadewar** [shihjay2/nosh2#83]
How this feature exactly works? I have created 2 requests but I am not able to see those request in Administrator panel.

Please suggest

**Comment by shihjay2** [comment]
What is your response immediately after you created the requests?  If you get "Try Again", that means that there is no matching patient in the system with the name and date of birth.

**Comment by ajinkyagadewar** [comment]
No as a admin I get an email saying "You have a new user request from  ABC with date and desired username". I am not able to understand where to accept the registration?

**Comment by shihjay2** [comment]
Login as a provider and enter the patients chart.  Under Demographics, and Contact click on Register to Portal.  Make sure that there is an email associated with the patient chart.  An email will be sent to the patient a time limited registration code.  That is the only way that a patient user can create their account.  If a patient is registering without a registration code an email will be sent to the admin email which is what you got which means that the patient never got a registration code or it has expired and the provider needs to regenerate the registration code.

**Comment by ajinkyagadewar** [comment]
Understood. Thanks.
