### ISSUE TITLE
Appointment Reminders

### ISSUE THREAD

**Issue by rumsant** [shihjay2/nosh2#84]
I am seeing a problem with appointment reminders in which the confirmation SMS or Email is successfully sent at the time an appointment is scheduled. However, the actually reminder is not sent in the day(s) prior to the appointment.

I am not sure about this, but it might be possible that this error began to occur at the time that you implemented the ability to changed the time prior to an appointment that the reminder was to be sent (i.e. 3 hours, 6 hours, 12 hours, 24 hours, or 48 hours prior).

**Comment by shihjay2** [comment]
Can you give me some data so that I an confirm that the logic is being processed correctly?  Make sure there are appointments that are set as Pended within the time frame that you have specified.  Make sure that the patient has a reminder method set.  Also indicate if you have a practice reminder interval set and a if applicable a patient reminder interval set for the appointment examples so I can troubleshoot.  Lastly, print the output of https://<your ip>/nosh/reminder and see if you get the correct number of appointment reminders sent out for that given time period.

**Comment by rumsant** [comment]
I can confirm without a doubt that there have been
1. appointments set as Pending within the applicable time frame
2. the patient has a reminder method set

As far as the "practice reminder interval" goes, I am assuming that is the setting under Configure>Practice Setup>Extensions. For that setting, I do not have "Appointment Reminder" enabled because I am under the impression that is not for reminders for scheduled appointments, but for a reminder if a specific time has lapsed since a patient's last appointment. The "Appointment Interval" for this setting is set at its default of "1 year", but I assume it is not applicable because I have the "Appointment Reminder Enabled" setting set to "no".

As for the https://nosh/reminder, I can see the output of that, but I'm not sure how to corroborate it with the schedule because I don't understand what you mean by "that given time period."

Of possible interest: I noticed that if I set the "Appointment Reminder Enabled" setting located in Configure>Practice Setup>Extensions to "yes", I am unable to bring up the https://nosh/reminder output. Instead I get an error page stating: "FatalThrowableError in Controller.php line 338:
Class 'App\Http\Controllers\Schedule' not found".

**Comment by shihjay2** [comment]
That helped me figure out where things went wrong.  I've made an update (this is a big one with some new translation/language files and an upcoming API that I've been working on for the past month) on commit 3600f214e6ab5f59097ed8010d4d4b69764f5461

**Comment by rumsant** [comment]
I did an update, and some testing, but the update does not appear to have fixed the failure to send the reminder.
Again, the confirmation SMS/Email is sent just fine when an appointment is scheduled, but the actual reminder is not being sent.
Is there any other information I can supply which might shed some light on this issue?

**Comment by shihjay2** [comment]
The only thing I could find is that SMS reminders might not be sent due to a character limit in some SMS carriers.  If I set the reminder to email for the patient, then the reminders are sent properly.  I've restructured the SMS text to use less characters.   I've updated the code in f25e4f28d1360a87c4cd4c3dd72176570d3d9ba0

**Comment by rumsant** [comment]
I'll have the check to see if the email reminder is working. I only tested the SMS with the last update.
It seems to me that it can't be a character limit issue because the SMS is sent just fine when scheduling the appointment.

**Comment by rumsant** [comment]
I have not been able to make any headway on this.

At the time an appointment is scheduled, the appropriate reminder/confirmation is sent successfully via both SMS and email with no problems.

However, there is no reminder sent 48 hours before the appointment with either SMS or email.

Any ideas on why this may be? My system is updated. Clearly my textbelt server and email are working, but the reminder is not getting triggered to send prior to the appointment. Could this have started when you included the ability of set a custom time prior to appointment for the reminder to be sent?

Thank you.

**Comment by shihjay2** [comment]
Are all reminders whether it is set at the default 48 hrs or any other not being sent?   If not, can you check if 
/etc/cron.d/nosh-cs exists and there is a line that refers to noshreminder?  

*/1 * * * * root /noshdocuments/nosh2/noshreminder
Make sure /noshdocuments/nosh2/noshreminder exists and looks the same as in the GitHub code.

**Comment by rumsant** [comment]
All reminders (except for the one sent immediately after scheduling the appt) are not being sent regardless of the time setting (12/24/48 hours, etc).

/etc/cron.d/nosh-cs exists and there is a line:
*/1 *   * * *   root    /noshdocuments/nosh2/noshreminder

/noshdocuments/nosh2/noshreminder does exist and looks identical to the GitHub code.

**Comment by shihjay2** [comment]
I'm not replicating this issue on my systems.
You need you to do this step by step and send me the results:

1. Create an appointment within 48 hours of when you created it.  You should get a reminder right away as you have indicated.  If you look on the schedule, status should be Pended.

2. Go to https://<your domain>/nosh/reminder on your browser.  You should get a reminder.  On the resulting response, there should be a line that says: Number of appointment reminders sent: 1.  If not, let me know.

3.  Change the appointment status on the schedule from Reminder Sent to Pended again.

4. Go to the terminal where NOSH is served and type in `wget --no-check-certificate -O - -q -t 1 localhost/nosh/reminder` (that's what is being run on the cron.d); you should get the same response (not as pretty but it's HTML).  If not, let me know.

5.  If none of these are working, make sure your system time is correct.

**Comment by rumsant** [comment]
At 7:55pm I made an appointment for 8:10 the following day (12hr15m in the future).
I did receive a reminder right away.
I went to .../nosh/reminder in my browser. I'm not sure if you meant I should get another reminder when I visited that address in my browser, but I did not get one regardless.
The result was "Number of appointment reminders sent: 0"

**Comment by shihjay2** [comment]
Did you check your system time?  It's clearly not identifying your current time correctly because it should register at least 1 appointment.

**Comment by shihjay2** [comment]
Do update_system and I introduced a hidden function.

Go to ../nosh/test1 and you should return a UNIX timestamp - that is the time currently.  Go to https://www.epochconverter.com/ and place that timestamp in Convert epoch to human readable date and vice versa to see if you got the right date.

**Comment by rumsant** [comment]
It is giving the correct date and time.
Just so strange because it had all been working just fine and then I realized at some point that the reminders weren't being sent out and I hadn't made any changes to the system.

**Comment by shihjay2** [comment]
Can you create another appointment within 48 hours and then do the ../nosh/reminder again and show me the first 2 lines, the first line should at least have at least 1.

**Comment by shihjay2** [comment]
I made another update to the code in possible situations where the appointment reminder interval was not saved correctly (if there was any saving of practice settings just after the custom time feature was added and maybe it saved the Default value as an empty string instead of 'Default' or NULL on the database.  If you did change the interval to something else for testing and saved it, it should have 'fixed' it but I'm trying to cover all the bases here to see if it applies to your case.

**Comment by rumsant** [comment]
My apologies for not getting back to you sooner. The total eclipse caused my son to turn into a werewolf. Very difficult to deal with.

Anyway, I updated, and I believe that things are working normally now. I will confirm it a few more times, but it looks good. Can't tell you how much I appreciate it. Thank you.

**Comment by rumsant** [comment]
I did a new install of NOSH-in-a-box on a different computer to see if reminders would work on a new system because even though I thought they were working last time you looked at this, I was mistaken.

In the process of testing reminders on the new system, I discovered something that may be the key to why reminders aren't working for me.

First of all, reminders did not work on the newly installed NOSH-in-a-box. The same behavior I outlined above was occurring with the new system. But what I discovered was that if I went to the /nosh/reminder page it would trigger the sending of any reminders that were due to go out around the time that I navigated to that page.

I tested this out on my older NOSH-in-a-box system and the same behavior occurred.

I'm really hoping that this is a clue as to why the reminders aren't being triggered automatically.

**Comment by shihjay2** [comment]
I've updated the NOSH-in-a-box code.  I figured out that there was a change in how Ubuntu addressed it's /etc/hosts file which was no longer needed anymore; so the latest release should work properly now.  If you don't want to create a new Vagrant release, do a `vagrant ssh`
then
`sudo nano /etc/hosts`
then make sure the contents look like this:
`127.0.0.1       localhost`
`::1     ip6-localhost   ip6-loopback`
`fe00::0 ip6-localnet`
`ff00::0 ip6-mcastprefix`
`ff02::1 ip6-allnodes`
`ff02::2 ip6-allrouters`
`ff02::3 ip6-allhosts`
`127.0.1.1       ubuntu-xenial   ubuntu-xenial`

**Comment by rumsant** [comment]
This appears to have resolved the issue. Awesome.
