### ISSUE TITLE
Getting errors on after installation

### ISSUE THREAD

**Issue by ajinkyagadewar** [shihjay2/nosh2#85]
This is happening after latest taking update of latest code.

UrlGenerationException in UrlGenerationException.php line 17:
Missing required parameters for [Route: users] [URI: users/{type}/{active}].

**Comment by shihjay2** [comment]
Fixed in commit d299c8b2bff74098a8a9cfebed47833aa3de08ac.  Please use URL https://<your_ip>/nosh/update_system to get the changes to take place.

**Comment by ajinkyagadewar** [comment]
Yes added the same code after getting the error :)
