### ISSUE TITLE
Recommendation Engine

### ISSUE THREAD

**Issue by ajinkyagadewar** [shihjay2/nosh2#86]
Hello Michael:
Just a thought.

Can we build any kind of recommendation engine for patients? We can get initial data from patients. 

Once the doctor sends the Registration Code, patient will access their portal and we can give them a wizard in which they will fill their basic details and vitals. We will process that data and show them if there is any risk with their health which can connected to patient education.

Thanks.

**Comment by shihjay2** [comment]
Have you tried the Care Opportunities feature in NOSH?  It is found on the left hand column when you enter a patient's chart (when a patient logs in, it automatically gets redirected to the patient's chart).  This is in essence a recommendations section that is based on 3 different metrics - one is with the US Preventative Services Task Force Recommendations, another is based on HEDIS (Healthcare Effectiveness Data and Information Set), and lastly, there is an ASCVD (Atherosclerotic Cardiovascular Disease) risk calculator (shows up dependent on age).  Those are the 3 that so far have sufficient evidence and support that provide general recommendations to patients.  Are there others that I'm not aware of (I'm a practicing family physician in the US) in other countries?

**Comment by ajinkyagadewar** [comment]
Sir:

I saw the Care Opportunities section and it is very helpful for Doctors but is there a way wherein system can recommend patient after entering his data. For example, after filling patient's data , system can tell whether he is having chances of Diabetics.

**Comment by ajinkyagadewar** [comment]
Did you get the chance to see this?

**Comment by shihjay2** [comment]
For your example above, I'm not aware of any evidence based algorithm that calculates a chance that an individual will get diabetes.  The Care Opportunity section is where a patient can begin a discussion with their physician about any risk reduction methods (ASCVD) and evidence based screening exams based on their gender, age, and habits.

**Comment by ajinkyagadewar** [comment]
Okay, got it. Thanks.
