### ISSUE TITLE
All Exports Throwing Error

### ISSUE THREAD

**Issue by ajinkyagadewar** [shihjay2/nosh2#87]
file_put_contents(https://*****/temp/1501676211_1_track): failed to open stream: HTTP wrapper does not support writeable connections

**Comment by shihjay2** [comment]
Cannot replicate.  Looking at the code, all calls for tracking progress involves creating a file through the Laravel wrapper public_path() which should return a fully qualified path to the public directory, not a URL.  The reason your error exists is that a URL to the _track file is being placed in file_put_contents.  Update the system and do this: https://<ip_address>/nosh/test1

That should return a fully qualified path (all that test1 function is returning public_path()).  If you're getting a URL return, something was configured that was outside the scope of Laravel/NOSH

**Comment by ajinkyagadewar** [comment]
As of now it is not returning anything.

**Comment by shihjay2** [comment]
Make sure you have used the update_system command.  It should return something as the public_path function is prevalent in NOSH.  Otherwise you would get lots of errors especially with printing prescriptions, orders, etc.

**Comment by ajinkyagadewar** [comment]
Yeah I am facing that issue.

**Comment by shihjay2** [comment]
You'll need to give me more information about your setup.  If you install via Vagrant, it should be working correctly out of the box.  If you have made changes to your operating system, PHP versions, etc, that's where you may run into trouble.

**Comment by shihjay2** [comment]
One thing you can do to trouble shoot is to Google l`laravel public_path not working` to get some ideas.

**Comment by ajinkyagadewar** [comment]
Thanks. Will do.
