### ISSUE TITLE
IPD 

### ISSUE THREAD

**Issue by ajinkyagadewar** [shihjay2/nosh2#88]
Sir:

Is there a way we can use nosh for IPD? Do you see any specific areas which needs to be customised for Beds and OT management?

**Comment by shihjay2** [comment]
Yes, there are differences in inpatient versus outpatient needs in an EHR.  NOSH's main focus right now is outpatient as that was the original intent of the design plus, I don't do much inpatient medicine anymore so my understand of the needs regarding clinical workflow are limited.  Of course other contributors who have experience in this can certainly help.
