### ISSUE TITLE
Problems trying to "inactivate" a user.

### ISSUE THREAD

**Issue by pastorcash** [shihjay2/nosh2#89]
Received the following message when trying to "inactive" a user record:

ErrorException in CoreController.php line 736:
Undefined index: firstname

I had a problem creating a new user. The system created (2) records for the same user. Now I am unable to modify the duplicate record in any way (no UserId) or inactivate it.

Also tried to inactivate a different user record due to the inability to reset the password ... same issue.

**Comment by shihjay2** [comment]
Please run https://<your domain or ip>/nosh/update_system in your browser and try again.  Fixed in commit 8554eda47af6dd2fb764b89d63daadfa4d09a16b

**Comment by pastorcash** [comment]
worked.

**Comment by pastorcash** [comment]
closed
