### ISSUE TITLE
Immediate "Code expired" for a password reset.

### ISSUE THREAD

**Issue by pastorcash** [shihjay2/nosh2#90]
Reguardless of whether the user requests a password reset or I do it as the Administrator ...
they receive the same error of an expired code.

**Comment by shihjay2** [comment]
Please run https://<your domain or ip>/nosh/update_system in your browser and try again.  Fixed in commit 8554eda47af6dd2fb764b89d63daadfa4d09a16b

**Comment by pastorcash** [comment]
worked
