### ISSUE TITLE
Had to add "credentials" to the back of an active "Physician" record. Lost the record. Unable to add new record with same email.

### ISSUE THREAD

**Issue by pastorcash** [shihjay2/nosh2#91]
When changing the name of user to add credentials (e.g. MS CCC/SLP) and updating the record. It completely disappeared. 
After trying to re-enter the user, receive the error message:
   "The email has already been taken." 

Considering the fact that all the users where initially entered without credentials and we now need to add them in order to comply with the requirements of having matching printed names and signatures on our documents -- I am in a little bit of a quandary for a work-a-round.

If I add the user with a new email ... the user cannot reuse the old "username" as well.
(obviously all forms associated with this user are no longer accessible as well)

**Comment by shihjay2** [comment]
I'm unable to replicate; can you go over exactly which fields you edited and what you added to each field?  For my testing, I did edits to the First Name, Last Name and Title fields.  Did you enter credentials to the Title fields?   Did you check to make sure you didn't inactivate the user inadvertently?  To check, you can click on the button that says Active Physicians, scroll and select Inactive Physicians to see if the user got placed there somehow.

**Comment by pastorcash** [comment]
Screen Shot 1 (Credentials 1) shows the active users prior to the test. Take note of the "Physician" Cashius Myers, MDiv.
![credentials 1](https://user-images.githubusercontent.com/22423719/30547165-2e240510-9c54-11e7-9c0b-aa4d8849e548.png)
Screen shot 2a/b show a before and after so that you can see what changes I made.
![credentials 2a](https://user-images.githubusercontent.com/22423719/30547167-2e378022-9c54-11e7-91f0-a71ef9708b36.png)
![credentials 2b](https://user-images.githubusercontent.com/22423719/30547168-2e3a3fba-9c54-11e7-863d-ed6b6f9d12c2.png)
Screen shot 3 shows the status of the physician record being dropped.
![credentials 3](https://user-images.githubusercontent.com/22423719/30547169-2e3b439c-9c54-11e7-8d86-5db8550c2545.png)
Screen shot 4 demonstrates that I validated that the record does NOT now appear on inactive physicians.
![credentials 4](https://user-images.githubusercontent.com/22423719/30547170-2e418694-9c54-11e7-8b17-0dd5036f5267.png)

**Comment by shihjay2** [comment]
Thanks for the screenshots; still trying to determine what is happening though.  When you do other edits (not changing the last name, but maybe the firstname), does it do the same thing or just only when you add credentials to the last name?

**Comment by pastorcash** [comment]
Not sure. Tried to create a dummy user to test this ... but it needs a valid email with USERID or an active user record. I have used up all of my personal emails testing this and I don't want to inactive a current user record. 
Is there a way to turn off the validation checking for either email or userid for updating a record?

**Comment by shihjay2** [comment]
OK, you can now do the update_system URL command and see if you can add a new user with the same email address for testing.

You can access the database directly by going to https://<your_ip_or_domain/phpmyadmin
Login is root and if you remember your MySQL password during the Vagrant install, that is the password you use to access the database (name of database is nosh).  Look in the users table and tell me what you see under the active column and practice_id column; that's where there is something unusual with the database updating.

**Comment by pastorcash** [comment]
I am striking out.
I decided to "vagrant destroy" and start over. After spending two days struggling through "minor" roadblock issues (like newly assigned IP's) ... I am unable to restore the saved database or add new users.
For the users ... I now have bad credentials. I have deleted, readded, refreshed, reloaded the JSON file from google multiple times. (see screen for error message) [Google help is no help.]
![user - bad credentials](https://user-images.githubusercontent.com/22423719/30712386-7b475a7a-9ed1-11e7-8434-5015095494af.png)

For the restore problem see the screen below.
![data restore problems](https://user-images.githubusercontent.com/22423719/30712705-8079e3d6-9ed2-11e7-96d2-877a59e57b98.png)

I have managed to get phpMyAdmin up, but without the data restore process happening, I am unable to examine the records.

**Comment by shihjay2** [comment]
When you mentioned that you had to make some changes to the IP, did you have to make changes to the domain?  If so, in the Google API configuration, have you updated the Authorized Redirect URL and regenerate the JSON file?  One thing you may want to check is to make sure that you can reach the machine from outside the LAN if you had to do some IP reconfiguration too.  For testing, I was trying to access the URL in the 2nd screenshot and I was unable to reach it so that may be the issue.

For the second screenshot and updating the database, were you able to get to the login screen as admin and did it show the restored database data from previous and you were trying to update the practice logo and this screenshot was the result?  Just wanted to know how you were restoring the data.

**Comment by pastorcash** [comment]
I was restoring from the only option on the admin menu. (Database: Import from NOSH in the Cloud) I then selected the zip file from a previous export of the "Entire Database (SQL format)"

**Comment by shihjay2** [comment]
OK, do an update_system call again and retry the same procedure (found an error in the upload process going to the wrong route) that you have been doing.

**Comment by pastorcash** [comment]
Screen shot 1
After running the local-ip script, I notice that vagrant reassigns a new ip (eg 192.168.0.171 to 192.168.0.163).
Thus I had to update my router port information records.
I think you couldn't get on to the "prtherapy123.com/nosh site" because I forgot to modify the vagrantfile to open up the system. I have halt and reloaded vagrant and tested it with my mobile phone externally to the local wi-fi. It seems to be working now.
If you would like: the admin is both the userid and the password for ease. You can sign in and try it.

**Comment by pastorcash** [comment]
Screen shot 2(a)
Ok new error message now.
![data restore problems 2](https://user-images.githubusercontent.com/22423719/30716101-674a821a-9ede-11e7-94b9-282d615615f8.png)

**Comment by shihjay2** [comment]
Please do update_system again for screenshot 2.  Thanks

**Comment by shihjay2** [comment]
For screenshot 1, I'd like to see once you restore your database if your errors for Gmail pop up again.

**Comment by pastorcash** [comment]
Okay I am getting a nosh error now:   _"Error - This is not a proper ZIP file. Missing SQL File."_
I tried two historical saves and the did a quick export of the new database and then immediately tried to restore it. Same error.
On a positive note. The logo is no longer disappearing. :)

**Comment by shihjay2** [comment]
Try update_system again for screenshot 2 and retry again.

**Comment by pastorcash** [comment]
It seemed to work once ... rcvd a completion message ... but no records were added.
Tried it a several times more and now each time receiving the same previous error message of not a proper zip file.

**Comment by shihjay2** [comment]
How did you verify that the records were not added; did you check the users list?  When you scan the compressed zip file, is there a file that ends in _noshexport.sql ?  The error message is the response looking for that particular file.

**Comment by pastorcash** [comment]
I did check the users list ... none were added. And I still have the "Users Needed" message showing up as well.
The compressed zip file has only one file in it - yes the compressed zip file does have the file you mentioned in it. 
I have extracted all of them from each save and loaded them into MySQL Workbench app for better clarity of viewing ... and unfortunately ... I cannot find the data dump of any of the other records ... only the administrator user.  (my apologies) (I am a bit disheartened to not see any data in any of the backups - I have 4)

**Comment by shihjay2** [comment]
I'm sorry to hear about the backups not being created as expected.  I'll look into it some further to see what may have happened. For future reference, I believe that automatic backups of the database occurs once a day and is saved in the /noshdocuments folder in the VM with the file extension .sql and a unix timestamp as part of the name.

Looking at your admin setup I noted that the value for Gmail account is admin@prtherapy123.com which doesn't look like a valid Gmail handle (has no @ in it and has to be associated with the Gmail account where you have activated the Google API.  That may be your problem.

**Comment by pastorcash** [comment]
The "prtherapy123.com" is a google suites account. Both "kimberly@prtherapy123.com" and "admin@prtherapy123.com" have been set up this way and both of them have been used as primary emails for the console.developers.google.com process that you described in your setup instructions. 
Not sure where you don't see the "@" sign ...

I double checked in the setup area and the "@" is listed (as well as in the Google API setup. )
I also validated through phpMyAdmin that the "@" is in the emails for both the "admin" user record and also the practiceinfo table.
Is it getting dropped during processing of the emails for validation?

By-the-way, I now have a "nosh_copy" of the database within phpMyAdmin. Not sure if you added it or if the restore database process did it.

On another note ... the "noshdocuments" folder is nowhere to found on my system. Is it a virtual folder within the linux/vagrant system or an actual windows directory like the nosh folder found in the specified user directory? Would this be part of the issue?

**Comment by shihjay2** [comment]
The nosh_copy was created when you performed the database export command.  If it looks like what you had before, you could just rename the database back to "nosh".  /noshdocuments is inside the vagrant system - not in the windows directory.

One thing, just to be sure, when you login to Google accounts under admin@prtherapy123.com, does it ask you for 2 factor authentication?  Has that been set up?  It may be looking to make sure since it's a "new" machine that it's rejecting the server for the first time until you respond appropriately.  See info about this in this thread https://www.digitalocean.com/community/questions/unable-to-send-mail-through-smtp-gmail-com

**Comment by pastorcash** [comment]
Ok. Good suggestion. I followed the thread and adjusted the setting per their suggestions. No effect.
So I created a brand new email "noshprtherapy@gmail.com", set up the console.developers info and still a bad result. The password for this email is "noshprtherapy123" if you wish to check on the settings here. 

I have updated the setup tab with the new password and reloaded the new JSON file.
I also manually added the password to the smtp_password field of the practiceinfo table and tried to add a user. 

The following is the screen shot
![email auth error](https://user-images.githubusercontent.com/22423719/30754986-1c4f1ff6-9f82-11e7-83ee-1b98317cb5df.png)

**Comment by shihjay2** [comment]
With the sending email function in NOSH, the smtp_pass field will change constantly as it's getting a token from Google that is associated with the JSON file you uploaded and matching with the Google ID; the reason I mentioned about the "@" character in a previous comment is that typically for this, that character is not needed (I don't know if that's the problem in your case); so the Google ID field value should be just "noshprtherapy" and not "noshprtherapy@gmail.com"; the fact that the smtp_pass field is blank means that Google is not recognizing your JSON file/with the username for some reason.

**Comment by pastorcash** [comment]
Ok so I changed the Gmail account and pulled out the "@gmail.com" portion. - Still received the same error. 
I am included my JSON file to see if it helps (converted to TXT file). At this point I am at a loss as what to do next.
[client_id 3.txt](https://github.com/shihjay2/nosh2/files/1325391/client_id.3.txt)

**Comment by shihjay2** [comment]
Try going to this URL http://prtherapy123.com/nosh/googleoauth and then select the noshprtherapy@gmail.com as your user if it asks you to select; let me know what the response to this is

**Comment by pastorcash** [comment]
This app isn't verified.  (Screen shots below) I allow access and then retry the googleoauth process

![verify 1](https://user-images.githubusercontent.com/22423719/30774898-768b1c68-a04f-11e7-93d4-afab6ed8b31b.png)

![verify 2](https://user-images.githubusercontent.com/22423719/30774897-76886b6c-a04f-11e7-8cfa-d57ef7d17d33.png)

. Same message occurs.

**Comment by pastorcash** [comment]
Question. If the SSL process for running letsencrypt did not complete, would that cause a problem?
If so how can I start over with just that process ? I've tried to rerun the process and it says that the directory already exists.

**Comment by shihjay2** [comment]
It's possible that could cause a problem.  Do you already have an SSL certificate for prtherapy123.com or are you needing to get one through Let'sEncrypt?  if you need to get one, log in to the Vagrant machine and enter these commands in the command-line.
`cd /usr/local/bin`
`wget https://dl.eff.org/certbot-auto`
`chmod a+x /usr/local/bin/certbot-auto`
`./certbot-auto --apache -d prtherapy123.com`

**Comment by shihjay2** [comment]
By the way, did you do a verification of application through Google?  I don't know exactly when Google started doing this but you may need to run through that first.

**Comment by pastorcash** [comment]
FOUND THE PROBLEM!!!
First - reapply for the SSL certificate corrected the errors for adding users.
Second - I went back to the original problem and examined the two fields you suggested (active and practice_id). The "active" still had its original value of "1", but the practice_id value was changed to "0". When I corrected it back to a "1" using phpMyAdmin. The record reappeared within Nosh.

Suggestion: Add the user's names to the "My information" screen. (Will accommodate practitioners who change their last names due to marriage,  or prefer a nickname, e.g. "Cash vs. Cashius" etc.)

**Comment by shihjay2** [comment]
I've improved the My Information screen to include ability to change name fields.  See commit 75a2f026c43495a432f65a3bfd9286b443169894

**Comment by pastorcash** [comment]
Installed the update. 
Tested using the my information screen. 
After making a change to my last name and updating the data, the practice_id was written with a "zero" value again. (Had to manually correct it using phpMyAdmin)

**Comment by shihjay2** [comment]
Update the system again and see if this works..  See commit 52f87a6f915c9d4b3dd8142257ff7a37bf78a341

**Comment by pastorcash** [comment]
Not sure that the new program compile took. The response was "No Update Needed." 
Both the user update screen from the Admin profile, and the My Information screen from a provider profile are still overwriting the practice_Id with a zero.

(I would try a compile on my own but I have taken the time or resources (box) to install a unix based system - plus my lack of experience with this op system puts me way behind the learning curve - so thank you for all of your efforts on this issue!)

**Comment by shihjay2** [comment]
The update probably took before you did the command (it updates every 24 hours automatically).  I made another try to see if this will work for you.  Do update_system again.  With the update, you'll see the practice ID field (you can't edit it, but it's for testing purposes).  See commit ae8d79ffeaa1bb783b9c87b6d7777a95c3bf73a0

**Comment by pastorcash** [comment]
It works!!
Closing this item out!
Thanks again.
