### ISSUE TITLE
How to run nosh2 without integrating to the Gmail Api

### ISSUE THREAD

**Issue by Sankethar** [shihjay2/nosh2#93]
Hi today i started using nosh2 i download the code and successfully installed in my localhost 
actually i am facing problem in Gmail API integration,
my question is can i run this application without integrate to the Gmail API

**Comment by shihjay2** [comment]
There are many functions that NOSH uses (for patient and provider notifications) that will not work unless you're using the Gmail API integration.  What problem are you having with getting the Gmail API to work? [ Did you follow these instructions?](https://github.com/shihjay2/nosh-in-a-box/wiki/How-to-get-Gmail-to-work-with-NOSH)

**Comment by Sankethar** [comment]
thank you it got resolved
