### ISSUE TITLE
Repeating schedule events fail to post

### ISSUE THREAD

**Issue by rumsant** [shihjay2/nosh2#94]
Scheduling a non-appointment event ("Other Event") with a repeater does not appear to work.
When saving the event, it stalls at the processing/loading stage and the event fails to show up on the schedule.
This appears to be the case regardless of whether an ending date is specified for the repeating event or not.

**Comment by shihjay2** [comment]
Fixed in commit 06046bbbb92e070a651134d1e51edab0cf958523
