### ISSUE TITLE
Importing Database

### ISSUE THREAD

**Issue by rumsant** [shihjay2/nosh2#97]
I'm guessing that I'm misunderstanding the correct way to do this.

I've exported a Database from the admin console of an instance of nosh-in-a-box via Export>Entire Database (SQL format).

Then in a new instance of nosh-in-a-box I am attempting to import that information via Database>Import from NOSH in the Cloud.

When I try to upload, I get an "Error - This is not a proper ZIP file. Missing SQL file."

Am I doing this wrong? If so, how would I go about restoring a backup or transferring a database from one instance of NOSH to a new installation?

**Comment by shihjay2** [comment]
Right now that functionality is not working correctly as NOSH in the Cloud has a different database architecture than what NOSH v2.0 is set up with so that would explain the errors.  Create backups and transfer the database using the command line when you're in the Vagrant system.

Create backup:
`mysqldump -u {username} -p{password - note no space between p and the password} nosh > nosh.sql`

You can use the scp command to copy the nosh.sql file from one system to another as long as the other is also connected in your network.

Once it's in the target machine, use the command
`mysql -u {username} -p {password, now there is a space after p} nosh < nosh.sql`

**Comment by rumsant** [comment]
Thanks. 
Trying to copy nosh.sql from the VM using the scp command, but I need to know the password for the ubuntu@ubuntu-xenial machine. I don't think that's something I set. Is it set within the NOSH system? And if so, what is it?

**Comment by shihjay2** [comment]
I'm assuming the ubuntu@ubuntal-xenial machine is your target and that you have already SSH'd into the machine where you generated the nosh.sql file.

The target machine, if you already ran NOSH in a Box from has the same username and password as what you set to access that machine's database.  If you don't remember or unable to recall it, I would not be able to help you and you'll need to reinstall the machine.  You would have had it set at the beginning of the installation.

So the command from the source machine would be
`cd <directory where nosh.sql resides>`
`scp nosh.sql <username of target machine>@<lan ip address of target machine>:/home/<username of target machine>`

It'll then ask for your password and then it'll proceed if successful.

**Comment by rumsant** [comment]
Thank you. I finally go t it.
I was confused by the fact that when I vagrant ssh the terminal prompt reads "ubuntu@ubuntu-xenial", so I was using "ubuntu" in my scp command. I should have been using the user that I set in the NOSH setup, and your comments eventually led me to that.

It appears as though this has worked for me to restore a backed up databse.

Am I correct in assuming that I will be unable to use the automatic backups that NOSH creates because of the "different database architecture" that you mentioned above?

Should I instead perform a manual mysql dump on a regular basis for backups?

**Comment by rumsant** [comment]
Also, for a complete backup would I want to backup the noshdocuments folder as well?

And have there been any updates that would contraindicate copying that noshdocuments folder into a new NOSH-in-a-box system? I ask because I see that there is a nosh2 folder in the noshdocuments folder, and I'm not sure if importing that into a new NOSH system would screw anything up.

**Comment by shihjay2** [comment]
One thing to comment as I'm building out a better backup/import/export system is there is currently a mechanism where backups are made automatically and stored in the /noshdocuments folder; however, this was also not working along with the reminder system, but should now be fixed.  You should see some *.sql files with a timestamp at the beginning of the file when the backup is made.

**Comment by rumsant** [comment]
Okay, I'll look for those.
I think I will try to find out how to script that mysqldump command and then try to automate that along with an rsync to external storage or something.

**Comment by shihjay2** [comment]
See commit d5a20d8ea74d99b0f746384af6c2614de6f7c10c for improvements in importing/exporting the database.

**Comment by rumsant** [comment]
Nice. That is exporting the .sql and the noshdocuments folder, correct?
Is there any backup process exporting this information in the background? I'm just wondering because I set up a cron job to do this yesterday and I want to make sure I'm not needlessly duplicating a process.
