### ISSUE TITLE
Unable to send fax

### ISSUE THREAD

**Issue by rumsant** [shihjay2/nosh2#98]
Trying to use the fax integration for the first time.
Not really sure about the technical details, but I'm assuming it's mostly baked-in to NOSH.
Signed up for phaxio account. Inserted API key and secret into NOSH.
When I try to send a fax to test this out, I get the following error:

"ErrorException in CoreController.php line 4673:
Undefined variable: faxnumber"

**Comment by shihjay2** [comment]
Addressed in commit d5a20d8ea74d99b0f746384af6c2614de6f7c10c.
